export const 
  playersList = [
    {
      "playerName": "Nikola Jokic",
      "avgFantasyScore": "41.91",
      "avgSingleGameHigh": "56.2",
      "avgTwoGameHigh": "52.672",
      "avgPTS": "29.6",
      "avgAST": "10.2",
      "avgTRB": "12.7",
      "avgFG3": "2",
      "avgBLK": "0.6",
      "avgSTL": "1.8",
      "avgTOV": "3.3",
      "MyRanking": "1",
      "Sleeper Rank": "1",
      "Discrepency": "0",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Giannis Antetokounmpo",
      "avgFantasyScore": "35.79",
      "avgSingleGameHigh": "48.2",
      "avgTwoGameHigh": "44.525",
      "avgPTS": "30.4",
      "avgAST": "6.5",
      "avgTRB": "11.9",
      "avgFG3": "0.2",
      "avgBLK": "1.2",
      "avgSTL": "0.9",
      "avgTOV": "3.1",
      "MyRanking": "2",
      "Sleeper Rank": "5",
      "Discrepency": "3",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Victor Wembanyama",
      "avgFantasyScore": "35.76",
      "avgSingleGameHigh": "48.29",
      "avgTwoGameHigh": "45.57",
      "avgPTS": "24.3",
      "avgAST": "3.7",
      "avgTRB": "11",
      "avgFG3": "3.1",
      "avgBLK": "3.8",
      "avgSTL": "1.1",
      "avgTOV": "3.2",
      "MyRanking": "3",
      "Sleeper Rank": "2",
      "Discrepency": "-1",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Luka Doncic",
      "avgFantasyScore": "33.15",
      "avgSingleGameHigh": "44.44",
      "avgTwoGameHigh": "39.655",
      "avgPTS": "28.2",
      "avgAST": "7.7",
      "avgTRB": "8.2",
      "avgFG3": "3.5",
      "avgBLK": "0.4",
      "avgSTL": "1.8",
      "avgTOV": "3.6",
      "MyRanking": "4",
      "Sleeper Rank": "3",
      "Discrepency": "-1",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Anthony Davis",
      "avgFantasyScore": "33",
      "avgSingleGameHigh": "45.06",
      "avgTwoGameHigh": "41.815",
      "avgPTS": "24.7",
      "avgAST": "3.5",
      "avgTRB": "11.6",
      "avgFG3": "0.7",
      "avgBLK": "2.2",
      "avgSTL": "1.2",
      "avgTOV": "2.2",
      "MyRanking": "5",
      "Sleeper Rank": "10",
      "Discrepency": "5",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Shai Gilgeous-Alexander",
      "avgFantasyScore": "32.2",
      "avgSingleGameHigh": "45.27",
      "avgTwoGameHigh": "41.25",
      "avgPTS": "32.7",
      "avgAST": "6.4",
      "avgTRB": "5",
      "avgFG3": "2.1",
      "avgBLK": "1",
      "avgSTL": "1.7",
      "avgTOV": "2.4",
      "MyRanking": "6",
      "Sleeper Rank": "4",
      "Discrepency": "-2",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Karl-Anthony Towns",
      "avgFantasyScore": "30.69",
      "avgSingleGameHigh": "40.73",
      "avgTwoGameHigh": "38.775",
      "avgPTS": "24.4",
      "avgAST": "3.1",
      "avgTRB": "12.8",
      "avgFG3": "2",
      "avgBLK": "0.7",
      "avgSTL": "1",
      "avgTOV": "2.7",
      "MyRanking": "7",
      "Sleeper Rank": "16",
      "Discrepency": "9",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Domantas Sabonis",
      "avgFantasyScore": "30.19",
      "avgSingleGameHigh": "39.2",
      "avgTwoGameHigh": "37.25",
      "avgPTS": "19.1",
      "avgAST": "6",
      "avgTRB": "13.9",
      "avgFG3": "0.9",
      "avgBLK": "0.4",
      "avgSTL": "0.7",
      "avgTOV": "2.9",
      "MyRanking": "8",
      "Sleeper Rank": "11",
      "Discrepency": "3",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "LeBron James",
      "avgFantasyScore": "29.32",
      "avgSingleGameHigh": "41.05",
      "avgTwoGameHigh": "37.775",
      "avgPTS": "24.4",
      "avgAST": "8.2",
      "avgTRB": "7.8",
      "avgFG3": "2.1",
      "avgBLK": "0.6",
      "avgSTL": "1",
      "avgTOV": "3.7",
      "MyRanking": "9",
      "Sleeper Rank": "15",
      "Discrepency": "6",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Cade Cunningham",
      "avgFantasyScore": "29.02",
      "avgSingleGameHigh": "40",
      "avgTwoGameHigh": "38.3",
      "avgPTS": "26.1",
      "avgAST": "9.1",
      "avgTRB": "6.1",
      "avgFG3": "2.1",
      "avgBLK": "0.8",
      "avgSTL": "1",
      "avgTOV": "4.4",
      "MyRanking": "10",
      "Sleeper Rank": "7",
      "Discrepency": "-3",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "James Harden",
      "avgFantasyScore": "28.02",
      "avgSingleGameHigh": "38.13",
      "avgTwoGameHigh": "36.395",
      "avgPTS": "22.8",
      "avgAST": "8.7",
      "avgTRB": "5.8",
      "avgFG3": "3",
      "avgBLK": "0.7",
      "avgSTL": "1.5",
      "avgTOV": "4.3",
      "MyRanking": "11",
      "Sleeper Rank": "44",
      "Discrepency": "33",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jalen Johnson",
      "avgFantasyScore": "27.81",
      "avgSingleGameHigh": "31.83",
      "avgTwoGameHigh": "30.71",
      "avgPTS": "18.9",
      "avgAST": "5",
      "avgTRB": "10",
      "avgFG3": "1.2",
      "avgBLK": "1",
      "avgSTL": "1.6",
      "avgTOV": "2.9",
      "MyRanking": "12",
      "Sleeper Rank": "18",
      "Discrepency": "6",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Trae Young",
      "avgFantasyScore": "26.97",
      "avgSingleGameHigh": "37.23",
      "avgTwoGameHigh": "35.705",
      "avgPTS": "24.2",
      "avgAST": "11.6",
      "avgTRB": "3.1",
      "avgFG3": "2.9",
      "avgBLK": "0.2",
      "avgSTL": "1.2",
      "avgTOV": "4.7",
      "MyRanking": "13",
      "Sleeper Rank": "21",
      "Discrepency": "8",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Alperen Sengun",
      "avgFantasyScore": "26.83",
      "avgSingleGameHigh": "36.14",
      "avgTwoGameHigh": "34.41",
      "avgPTS": "19.1",
      "avgAST": "4.9",
      "avgTRB": "10.3",
      "avgFG3": "0.3",
      "avgBLK": "0.8",
      "avgSTL": "1.1",
      "avgTOV": "2.6",
      "MyRanking": "14",
      "Sleeper Rank": "24",
      "Discrepency": "10",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Anthony Edwards",
      "avgFantasyScore": "26.8",
      "avgSingleGameHigh": "36.54",
      "avgTwoGameHigh": "34.105",
      "avgPTS": "27.6",
      "avgAST": "4.5",
      "avgTRB": "5.7",
      "avgFG3": "4.1",
      "avgBLK": "0.6",
      "avgSTL": "1.2",
      "avgTOV": "3.2",
      "MyRanking": "15",
      "Sleeper Rank": "8",
      "Discrepency": "-7",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Ivica Zubac",
      "avgFantasyScore": "26.46",
      "avgSingleGameHigh": "36.33",
      "avgTwoGameHigh": "34.645",
      "avgPTS": "16.8",
      "avgAST": "2.7",
      "avgTRB": "12.6",
      "avgFG3": "0",
      "avgBLK": "1.1",
      "avgSTL": "0.7",
      "avgTOV": "1.6",
      "MyRanking": "16",
      "Sleeper Rank": "46",
      "Discrepency": "30",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Paolo Banchero",
      "avgFantasyScore": "26.39",
      "avgSingleGameHigh": "38.21",
      "avgTwoGameHigh": "35.32",
      "avgPTS": "25.9",
      "avgAST": "4.8",
      "avgTRB": "7.5",
      "avgFG3": "1.9",
      "avgBLK": "0.6",
      "avgSTL": "0.8",
      "avgTOV": "3",
      "MyRanking": "17",
      "Sleeper Rank": "6",
      "Discrepency": "-11",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Tyrese Maxey",
      "avgFantasyScore": "26.37",
      "avgSingleGameHigh": "26.5",
      "avgTwoGameHigh": "34.095",
      "avgPTS": "26.3",
      "avgAST": "6.1",
      "avgTRB": "3.3",
      "avgFG3": "3.1",
      "avgBLK": "0.4",
      "avgSTL": "1.8",
      "avgTOV": "2.4",
      "MyRanking": "18",
      "Sleeper Rank": "19",
      "Discrepency": "1",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Scottie Barnes",
      "avgFantasyScore": "26.12",
      "avgSingleGameHigh": "36.4",
      "avgTwoGameHigh": "33.925",
      "avgPTS": "19.3",
      "avgAST": "5.8",
      "avgTRB": "7.7",
      "avgFG3": "1.2",
      "avgBLK": "1",
      "avgSTL": "1.4",
      "avgTOV": "2.8",
      "MyRanking": "19",
      "Sleeper Rank": "17",
      "Discrepency": "-2",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Kevin Durant",
      "avgFantasyScore": "26.02",
      "avgSingleGameHigh": "34.89",
      "avgTwoGameHigh": "33.335",
      "avgPTS": "19.3",
      "avgAST": "5.8",
      "avgTRB": "7.7",
      "avgFG3": "1.2",
      "avgBLK": "1",
      "avgSTL": "1.4",
      "avgTOV": "2.8",
      "MyRanking": "20",
      "Sleeper Rank": "28",
      "Discrepency": "8",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Nikola Vucevic",
      "avgFantasyScore": "25.79",
      "avgSingleGameHigh": "34.59",
      "avgTwoGameHigh": "32.91",
      "avgPTS": "26.6",
      "avgAST": "4.2",
      "avgTRB": "6",
      "avgFG3": "2.6",
      "avgBLK": "1.2",
      "avgSTL": "0.8",
      "avgTOV": "3.1",
      "MyRanking": "21",
      "Sleeper Rank": "106",
      "Discrepency": "85",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Bam Adebayo",
      "avgFantasyScore": "25.78",
      "avgSingleGameHigh": "36.42",
      "avgTwoGameHigh": "32.395",
      "avgPTS": "18.5",
      "avgAST": "3.5",
      "avgTRB": "10.1",
      "avgFG3": "1.8",
      "avgBLK": "0.7",
      "avgSTL": "0.8",
      "avgTOV": "1.6",
      "MyRanking": "22",
      "Sleeper Rank": "38",
      "Discrepency": "16",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Evan Mobley",
      "avgFantasyScore": "25.74",
      "avgSingleGameHigh": "36.23",
      "avgTwoGameHigh": "32.34",
      "avgPTS": "18.1",
      "avgAST": "4.3",
      "avgTRB": "9.6",
      "avgFG3": "1",
      "avgBLK": "0.7",
      "avgSTL": "1.3",
      "avgTOV": "2.1",
      "MyRanking": "23",
      "Sleeper Rank": "14",
      "Discrepency": "-9",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Stephen Curry",
      "avgFantasyScore": "25.41",
      "avgSingleGameHigh": "37.4",
      "avgTwoGameHigh": "33.9",
      "avgPTS": "18.5",
      "avgAST": "3.2",
      "avgTRB": "9.3",
      "avgFG3": "1.2",
      "avgBLK": "1.6",
      "avgSTL": "0.9",
      "avgTOV": "2",
      "MyRanking": "24",
      "Sleeper Rank": "13",
      "Discrepency": "-11",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Josh Hart",
      "avgFantasyScore": "25.12",
      "avgSingleGameHigh": "35.64",
      "avgTwoGameHigh": "33.365",
      "avgPTS": "24.5",
      "avgAST": "6",
      "avgTRB": "4.4",
      "avgFG3": "4.4",
      "avgBLK": "0.4",
      "avgSTL": "1.1",
      "avgTOV": "2.9",
      "MyRanking": "25",
      "Sleeper Rank": "112",
      "Discrepency": "87",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "De'Aaron Fox",
      "avgFantasyScore": "24.99",
      "avgSingleGameHigh": "35.44",
      "avgTwoGameHigh": "32.36",
      "avgPTS": "17.5",
      "avgAST": "7.4",
      "avgTRB": "6.5",
      "avgFG3": "1.7",
      "avgBLK": "0.4",
      "avgSTL": "2",
      "avgTOV": "3.4",
      "MyRanking": "27",
      "Sleeper Rank": "29",
      "Discrepency": "2",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Devin Booker",
      "avgFantasyScore": "24.73",
      "avgSingleGameHigh": "34.82",
      "avgTwoGameHigh": "32.68",
      "avgPTS": "23.5",
      "avgAST": "6.3",
      "avgTRB": "4.8",
      "avgFG3": "1.9",
      "avgBLK": "0.4",
      "avgSTL": "1.5",
      "avgTOV": "2.8",
      "MyRanking": "28",
      "Sleeper Rank": "22",
      "Discrepency": "-6",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Josh Giddey",
      "avgFantasyScore": "24.65",
      "avgSingleGameHigh": "36.7",
      "avgTwoGameHigh": "34.2",
      "avgPTS": "25.6",
      "avgAST": "7.1",
      "avgTRB": "4.1",
      "avgFG3": "2.4",
      "avgBLK": "0.2",
      "avgSTL": "0.9",
      "avgTOV": "2.9",
      "MyRanking": "29",
      "Sleeper Rank": "36",
      "Discrepency": "7",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jalen Williams",
      "avgFantasyScore": "24.62",
      "avgSingleGameHigh": "34.2",
      "avgTwoGameHigh": "32.7",
      "avgPTS": "14.6",
      "avgAST": "7.2",
      "avgTRB": "8.1",
      "avgFG3": "1.5",
      "avgBLK": "0.6",
      "avgSTL": "1.2",
      "avgTOV": "2.9",
      "MyRanking": "30",
      "Sleeper Rank": "37",
      "Discrepency": "7",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "LaMelo Ball",
      "avgFantasyScore": "24.46",
      "avgSingleGameHigh": "36.29",
      "avgTwoGameHigh": "34.215",
      "avgPTS": "21.6",
      "avgAST": "5.1",
      "avgTRB": "5.3",
      "avgFG3": "1.8",
      "avgBLK": "0.7",
      "avgSTL": "1.6",
      "avgTOV": "2.2",
      "MyRanking": "31",
      "Sleeper Rank": "20",
      "Discrepency": "-11",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Walker Kessler",
      "avgFantasyScore": "24.44",
      "avgSingleGameHigh": "35.56",
      "avgTwoGameHigh": "32.055",
      "avgPTS": "25.2",
      "avgAST": "7.4",
      "avgTRB": "4.9",
      "avgFG3": "3.8",
      "avgBLK": "0.3",
      "avgSTL": "1.1",
      "avgTOV": "3.6",
      "MyRanking": "32",
      "Sleeper Rank": "55",
      "Discrepency": "23",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Franz Wagner",
      "avgFantasyScore": "24.32",
      "avgSingleGameHigh": "31.67",
      "avgTwoGameHigh": "29.945",
      "avgPTS": "11.1",
      "avgAST": "1.7",
      "avgTRB": "12.2",
      "avgFG3": "0.1",
      "avgBLK": "2.4",
      "avgSTL": "0.6",
      "avgTOV": "1.5",
      "MyRanking": "33",
      "Sleeper Rank": "26",
      "Discrepency": "-7",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Donovan Mitchell",
      "avgFantasyScore": "24.31",
      "avgSingleGameHigh": "32.32",
      "avgTwoGameHigh": "30.475",
      "avgPTS": "24.1",
      "avgAST": "4.7",
      "avgTRB": "5.7",
      "avgFG3": "1.7",
      "avgBLK": "0.3",
      "avgSTL": "1.3",
      "avgTOV": "2.3",
      "MyRanking": "34",
      "Sleeper Rank": "31",
      "Discrepency": "-3",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jalen Brunson",
      "avgFantasyScore": "24.23",
      "avgSingleGameHigh": "32.05",
      "avgTwoGameHigh": "30.725",
      "avgPTS": "24",
      "avgAST": "5",
      "avgTRB": "4.5",
      "avgFG3": "3.3",
      "avgBLK": "0.2",
      "avgSTL": "1.3",
      "avgTOV": "2.1",
      "MyRanking": "35",
      "Sleeper Rank": "27",
      "Discrepency": "-8",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Tyler Herro",
      "avgFantasyScore": "24.05",
      "avgSingleGameHigh": "34.91",
      "avgTwoGameHigh": "32.205",
      "avgPTS": "26",
      "avgAST": "7.3",
      "avgTRB": "2.9",
      "avgFG3": "2.3",
      "avgBLK": "0.1",
      "avgSTL": "0.9",
      "avgTOV": "2.5",
      "MyRanking": "36",
      "Sleeper Rank": "39",
      "Discrepency": "3",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jamal Murray",
      "avgFantasyScore": "23.57",
      "avgSingleGameHigh": "33.6",
      "avgTwoGameHigh": "31.025",
      "avgPTS": "23.9",
      "avgAST": "5.5",
      "avgTRB": "5.2",
      "avgFG3": "3.3",
      "avgBLK": "0.2",
      "avgSTL": "0.9",
      "avgTOV": "2.6",
      "MyRanking": "37",
      "Sleeper Rank": "41",
      "Discrepency": "4",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Miles Bridges",
      "avgFantasyScore": "23.57",
      "avgSingleGameHigh": "34.15",
      "avgTwoGameHigh": "29.8",
      "avgPTS": "21.4",
      "avgAST": "6",
      "avgTRB": "3.9",
      "avgFG3": "2.3",
      "avgBLK": "0.5",
      "avgSTL": "1.4",
      "avgTOV": "2.1",
      "MyRanking": "38",
      "Sleeper Rank": "87",
      "Discrepency": "49",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Dyson Daniels",
      "avgFantasyScore": "23.43",
      "avgSingleGameHigh": "30.86",
      "avgTwoGameHigh": "29.475",
      "avgPTS": "20.3",
      "avgAST": "3.9",
      "avgTRB": "7.5",
      "avgFG3": "2.2",
      "avgBLK": "0.7",
      "avgSTL": "0.7",
      "avgTOV": "2.1",
      "MyRanking": "39",
      "Sleeper Rank": "48",
      "Discrepency": "9",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Ja Morant",
      "avgFantasyScore": "23.39",
      "avgSingleGameHigh": "32.56",
      "avgTwoGameHigh": "28.22",
      "avgPTS": "14.1",
      "avgAST": "4.4",
      "avgTRB": "5.9",
      "avgFG3": "1.1",
      "avgBLK": "0.7",
      "avgSTL": "3",
      "avgTOV": "2",
      "MyRanking": "40",
      "Sleeper Rank": "51",
      "Discrepency": "11",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jaren Jackson Jr.",
      "avgFantasyScore": "23.29",
      "avgSingleGameHigh": "33.09",
      "avgTwoGameHigh": "30",
      "avgPTS": "23.2",
      "avgAST": "7.3",
      "avgTRB": "4.1",
      "avgFG3": "1.8",
      "avgBLK": "0.2",
      "avgSTL": "1.2",
      "avgTOV": "3.7",
      "MyRanking": "41",
      "Sleeper Rank": "23",
      "Discrepency": "-18",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Kawhi Leonard",
      "avgFantasyScore": "23.16",
      "avgSingleGameHigh": "30",
      "avgTwoGameHigh": "28.25",
      "avgPTS": "22.2",
      "avgAST": "2",
      "avgTRB": "5.6",
      "avgFG3": "2",
      "avgBLK": "1.5",
      "avgSTL": "1.2",
      "avgTOV": "2.1",
      "MyRanking": "42",
      "Sleeper Rank": "108",
      "Discrepency": "66",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Kristaps Porzingis",
      "avgFantasyScore": "23.15",
      "avgSingleGameHigh": "32.5",
      "avgTwoGameHigh": "31.165",
      "avgPTS": "21.5",
      "avgAST": "3.1",
      "avgTRB": "5.9",
      "avgFG3": "2.1",
      "avgBLK": "0.5",
      "avgSTL": "1.6",
      "avgTOV": "1.9",
      "MyRanking": "43",
      "Sleeper Rank": "63",
      "Discrepency": "20",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Desmond Bane",
      "avgFantasyScore": "23.08",
      "avgSingleGameHigh": "33.55",
      "avgTwoGameHigh": "30.875",
      "avgPTS": "19.5",
      "avgAST": "2.1",
      "avgTRB": "6.8",
      "avgFG3": "2.5",
      "avgBLK": "1.5",
      "avgSTL": "0.7",
      "avgTOV": "1.3",
      "MyRanking": "44",
      "Sleeper Rank": "49",
      "Discrepency": "5",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Mark Williams",
      "avgFantasyScore": "23.03",
      "avgSingleGameHigh": "30.93",
      "avgTwoGameHigh": "29.395",
      "avgPTS": "19.2",
      "avgAST": "5.3",
      "avgTRB": "6.1",
      "avgFG3": "2.4",
      "avgBLK": "0.4",
      "avgSTL": "1.2",
      "avgTOV": "2.4",
      "MyRanking": "45",
      "Sleeper Rank": "100",
      "Discrepency": "55",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Amen Thompson",
      "avgFantasyScore": "22.96",
      "avgSingleGameHigh": "33.25",
      "avgTwoGameHigh": "31.075",
      "avgPTS": "15.3",
      "avgAST": "2.5",
      "avgTRB": "10.2",
      "avgFG3": "0",
      "avgBLK": "1.2",
      "avgSTL": "0.7",
      "avgTOV": "1.6",
      "MyRanking": "46",
      "Sleeper Rank": "25",
      "Discrepency": "-21",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jakob Poeltl",
      "avgFantasyScore": "22.87",
      "avgSingleGameHigh": "31.5",
      "avgTwoGameHigh": "28.585",
      "avgPTS": "14.1",
      "avgAST": "3.8",
      "avgTRB": "8.2",
      "avgFG3": "0.4",
      "avgBLK": "1.3",
      "avgSTL": "1.4",
      "avgTOV": "2",
      "MyRanking": "47",
      "Sleeper Rank": "85",
      "Discrepency": "38",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jaylen Brown",
      "avgFantasyScore": "22.86",
      "avgSingleGameHigh": "31.61",
      "avgTwoGameHigh": "29.555",
      "avgPTS": "14.5",
      "avgAST": "2.8",
      "avgTRB": "9.6",
      "avgFG3": "0",
      "avgBLK": "1.2",
      "avgSTL": "1.2",
      "avgTOV": "1.9",
      "MyRanking": "38",
      "Sleeper Rank": "45",
      "Discrepency": "-7",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Pascal Siakam",
      "avgFantasyScore": "22.83",
      "avgSingleGameHigh": "32.21",
      "avgTwoGameHigh": "28.79",
      "avgPTS": "22.2",
      "avgAST": "4.5",
      "avgTRB": "5.8",
      "avgFG3": "1.8",
      "avgBLK": "0.3",
      "avgSTL": "1.2",
      "avgTOV": "2.6",
      "MyRanking": "42",
      "Sleeper Rank": "62",
      "Discrepency": "20",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Isaiah Hartenstein",
      "avgFantasyScore": "22.78",
      "avgSingleGameHigh": "30",
      "avgTwoGameHigh": "26.915",
      "avgPTS": "20.2",
      "avgAST": "3.4",
      "avgTRB": "6.9",
      "avgFG3": "1.6",
      "avgBLK": "0.5",
      "avgSTL": "0.9",
      "avgTOV": "1.4",
      "MyRanking": "50",
      "Sleeper Rank": "74",
      "Discrepency": "24",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "RJ Barrett",
      "avgFantasyScore": "22.72",
      "avgSingleGameHigh": "29.89",
      "avgTwoGameHigh": "28.165",
      "avgPTS": "11.2",
      "avgAST": "3.8",
      "avgTRB": "10.7",
      "avgFG3": "0",
      "avgBLK": "1.1",
      "avgSTL": "0.8",
      "avgTOV": "1.7",
      "MyRanking": "51",
      "Sleeper Rank": "138",
      "Discrepency": "87",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Chet Holmgren",
      "avgFantasyScore": "22.64",
      "avgSingleGameHigh": "36.2",
      "avgTwoGameHigh": "32.25",
      "avgPTS": "21.1",
      "avgAST": "5.4",
      "avgTRB": "6.3",
      "avgFG3": "1.8",
      "avgBLK": "0.3",
      "avgSTL": "0.8",
      "avgTOV": "2.8",
      "MyRanking": "52",
      "Sleeper Rank": "40",
      "Discrepency": "-12",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Trey Murphy III",
      "avgFantasyScore": "22.42",
      "avgSingleGameHigh": "28.75",
      "avgTwoGameHigh": "27.44",
      "avgPTS": "15",
      "avgAST": "2",
      "avgTRB": "8",
      "avgFG3": "1.4",
      "avgBLK": "2.2",
      "avgSTL": "0.7",
      "avgTOV": "1.8",
      "MyRanking": "53",
      "Sleeper Rank": "30",
      "Discrepency": "-23",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Rudy Gobert",
      "avgFantasyScore": "22.39",
      "avgSingleGameHigh": "32",
      "avgTwoGameHigh": "30.365",
      "avgPTS": "21.2",
      "avgAST": "3.5",
      "avgTRB": "5.1",
      "avgFG3": "3",
      "avgBLK": "0.7",
      "avgSTL": "1.1",
      "avgTOV": "1.9",
      "MyRanking": "54",
      "Sleeper Rank": "117",
      "Discrepency": "63",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Austin Reaves",
      "avgFantasyScore": "22.31",
      "avgSingleGameHigh": "32.23",
      "avgTwoGameHigh": "29.885",
      "avgPTS": "12",
      "avgAST": "1.8",
      "avgTRB": "10.9",
      "avgFG3": "0",
      "avgBLK": "1.4",
      "avgSTL": "0.8",
      "avgTOV": "1.2",
      "MyRanking": "55",
      "Sleeper Rank": "43",
      "Discrepency": "-12",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Brandon Ingram",
      "avgFantasyScore": "22.19",
      "avgSingleGameHigh": "30.17",
      "avgTwoGameHigh": "28.5",
      "avgPTS": "20.2",
      "avgAST": "5.8",
      "avgTRB": "4.5",
      "avgFG3": "2.7",
      "avgBLK": "0.3",
      "avgSTL": "1.1",
      "avgTOV": "2.4",
      "MyRanking": "56",
      "Sleeper Rank": "65",
      "Discrepency": "9",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jimmy Butler",
      "avgFantasyScore": "22.13",
      "avgSingleGameHigh": "35.94",
      "avgTwoGameHigh": "32.095",
      "avgPTS": "22.2",
      "avgAST": "5.2",
      "avgTRB": "5.6",
      "avgFG3": "2.4",
      "avgBLK": "0.6",
      "avgSTL": "0.9",
      "avgTOV": "3.8",
      "MyRanking": "57",
      "Sleeper Rank": "95",
      "Discrepency": "38",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "John Collins",
      "avgFantasyScore": "22.09",
      "avgSingleGameHigh": "31.5",
      "avgTwoGameHigh": "29.375",
      "avgPTS": "17.5",
      "avgAST": "5.4",
      "avgTRB": "5.4",
      "avgFG3": "0.6",
      "avgBLK": "0.3",
      "avgSTL": "1.4",
      "avgTOV": "1.3",
      "MyRanking": "87",
      "Sleeper Rank": "145",
      "Discrepency": "58",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Brandon Miller",
      "avgFantasyScore": "21.81",
      "avgSingleGameHigh": "32.13",
      "avgTwoGameHigh": "29.125",
      "avgPTS": "18.9",
      "avgAST": "2",
      "avgTRB": "8.2",
      "avgFG3": "1.5",
      "avgBLK": "1",
      "avgSTL": "1",
      "avgTOV": "2.6",
      "MyRanking": "59",
      "Sleeper Rank": "34",
      "Discrepency": "-25",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Darius Garland",
      "avgFantasyScore": "21.6",
      "avgSingleGameHigh": "29.55",
      "avgTwoGameHigh": "27.59",
      "avgPTS": "21",
      "avgAST": "3.6",
      "avgTRB": "4.9",
      "avgFG3": "3.9",
      "avgBLK": "0.7",
      "avgSTL": "1.1",
      "avgTOV": "2.8",
      "MyRanking": "60",
      "Sleeper Rank": "32",
      "Discrepency": "-28",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Derrick White",
      "avgFantasyScore": "21.55",
      "avgSingleGameHigh": "28.32",
      "avgTwoGameHigh": "27.225",
      "avgPTS": "20.6",
      "avgAST": "6.7",
      "avgTRB": "2.9",
      "avgFG3": "2.8",
      "avgBLK": "0.1",
      "avgSTL": "1.2",
      "avgTOV": "2.5",
      "MyRanking": "55",
      "Sleeper Rank": "76",
      "Discrepency": "21",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jalen Duren",
      "avgFantasyScore": "21.36",
      "avgSingleGameHigh": "30.25",
      "avgTwoGameHigh": "27.605",
      "avgPTS": "16.4",
      "avgAST": "4.8",
      "avgTRB": "4.5",
      "avgFG3": "3.5",
      "avgBLK": "1.1",
      "avgSTL": "0.9",
      "avgTOV": "1.7",
      "MyRanking": "62",
      "Sleeper Rank": "68",
      "Discrepency": "6",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jarrett Allen",
      "avgFantasyScore": "21.35",
      "avgSingleGameHigh": "32.67",
      "avgTwoGameHigh": "30.875",
      "avgPTS": "11.8",
      "avgAST": "2.7",
      "avgTRB": "10.3",
      "avgFG3": "0",
      "avgBLK": "1.1",
      "avgSTL": "0.7",
      "avgTOV": "1.7",
      "MyRanking": "63",
      "Sleeper Rank": "66",
      "Discrepency": "3",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Deandre Ayton",
      "avgFantasyScore": "21.3",
      "avgSingleGameHigh": "31.92",
      "avgTwoGameHigh": "29.415",
      "avgPTS": "13.5",
      "avgAST": "1.9",
      "avgTRB": "9.7",
      "avgFG3": "0",
      "avgBLK": "0.9",
      "avgSTL": "0.9",
      "avgTOV": "1.2",
      "MyRanking": "64",
      "Sleeper Rank": "128",
      "Discrepency": "64",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "DeMar DeRozan",
      "avgFantasyScore": "21.1",
      "avgSingleGameHigh": "31.14",
      "avgTwoGameHigh": "28.635",
      "avgPTS": "14.4",
      "avgAST": "1.6",
      "avgTRB": "10.2",
      "avgFG3": "0.1",
      "avgBLK": "1",
      "avgSTL": "0.8",
      "avgTOV": "1.7",
      "MyRanking": "65",
      "Sleeper Rank": "105",
      "Discrepency": "40",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Paul George",
      "avgFantasyScore": "21.09",
      "avgSingleGameHigh": "30.67",
      "avgTwoGameHigh": "28.665",
      "avgPTS": "22.2",
      "avgAST": "4.4",
      "avgTRB": "3.9",
      "avgFG3": "1.1",
      "avgBLK": "0.4",
      "avgSTL": "0.8",
      "avgTOV": "1.4",
      "MyRanking": "66",
      "Sleeper Rank": "111",
      "Discrepency": "45",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Onyeka Okongwu",
      "avgFantasyScore": "21.05",
      "avgSingleGameHigh": "31.68",
      "avgTwoGameHigh": "29.91",
      "avgPTS": "16.2",
      "avgAST": "4.3",
      "avgTRB": "5.3",
      "avgFG3": "2.3",
      "avgBLK": "0.5",
      "avgSTL": "1.8",
      "avgTOV": "2.6",
      "MyRanking": "67",
      "Sleeper Rank": "80",
      "Discrepency": "13",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Julius Randle",
      "avgFantasyScore": "21.04",
      "avgSingleGameHigh": "29.9",
      "avgTwoGameHigh": "27.9",
      "avgPTS": "13.4",
      "avgAST": "2.3",
      "avgTRB": "8.9",
      "avgFG3": "0.6",
      "avgBLK": "0.9",
      "avgSTL": "0.9",
      "avgTOV": "1.2",
      "MyRanking": "68",
      "Sleeper Rank": "126",
      "Discrepency": "58",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Deni Avdija",
      "avgFantasyScore": "20.97",
      "avgSingleGameHigh": "30.86",
      "avgTwoGameHigh": "29.525",
      "avgPTS": "18.7",
      "avgAST": "4.7",
      "avgTRB": "7.1",
      "avgFG3": "1.6",
      "avgBLK": "0.2",
      "avgSTL": "0.7",
      "avgTOV": "2.8",
      "MyRanking": "69",
      "Sleeper Rank": "50",
      "Discrepency": "-19",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Zach Lavine",
      "avgFantasyScore": "20.93",
      "avgSingleGameHigh": "29.68",
      "avgTwoGameHigh": "27.34",
      "avgPTS": "16.9",
      "avgAST": "3.9",
      "avgTRB": "7.3",
      "avgFG3": "1.7",
      "avgBLK": "0.5",
      "avgSTL": "1",
      "avgTOV": "2.7",
      "MyRanking": "70",
      "Sleeper Rank": "60",
      "Discrepency": "-10",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Myles Turner",
      "avgFantasyScore": "20.92",
      "avgSingleGameHigh": "30.18",
      "avgTwoGameHigh": "27.25",
      "avgPTS": "23.3",
      "avgAST": "4.2",
      "avgTRB": "4.3",
      "avgFG3": "3.2",
      "avgBLK": "0.2",
      "avgSTL": "0.8",
      "avgTOV": "2.8",
      "MyRanking": "71",
      "Sleeper Rank": "61",
      "Discrepency": "-10",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "P.J. Washington",
      "avgFantasyScore": "20.68",
      "avgSingleGameHigh": "29.44",
      "avgTwoGameHigh": "26.305",
      "avgPTS": "15.6",
      "avgAST": "1.5",
      "avgTRB": "6.5",
      "avgFG3": "2.2",
      "avgBLK": "2",
      "avgSTL": "0.8",
      "avgTOV": "1.7",
      "MyRanking": "72",
      "Sleeper Rank": "114",
      "Discrepency": "42",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "CJ McCollum",
      "avgFantasyScore": "20.64",
      "avgSingleGameHigh": "32.19",
      "avgTwoGameHigh": "29.22",
      "avgPTS": "14.7",
      "avgAST": "2.3",
      "avgTRB": "7.8",
      "avgFG3": "1.6",
      "avgBLK": "1.1",
      "avgSTL": "1.1",
      "avgTOV": "2.1",
      "MyRanking": "73",
      "Sleeper Rank": "158",
      "Discrepency": "85",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Michael Porter Jr.",
      "avgFantasyScore": "20.62",
      "avgSingleGameHigh": "29.09",
      "avgTwoGameHigh": "27.07",
      "avgPTS": "21.1",
      "avgAST": "4.1",
      "avgTRB": "3.8",
      "avgFG3": "3.1",
      "avgBLK": "0.4",
      "avgSTL": "0.8",
      "avgTOV": "1.9",
      "MyRanking": "74",
      "Sleeper Rank": "118",
      "Discrepency": "44",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "OG Anunoby",
      "avgFantasyScore": "20.57",
      "avgSingleGameHigh": "30.59",
      "avgTwoGameHigh": "28.455",
      "avgPTS": "18.2",
      "avgAST": "2.1",
      "avgTRB": "7",
      "avgFG3": "2.5",
      "avgBLK": "0.5",
      "avgSTL": "0.6",
      "avgTOV": "1.4",
      "MyRanking": "75",
      "Sleeper Rank": "73",
      "Discrepency": "-2",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Fred VanVleet",
      "avgFantasyScore": "20.18",
      "avgSingleGameHigh": "28.22",
      "avgTwoGameHigh": "26.14",
      "avgPTS": "18",
      "avgAST": "2.2",
      "avgTRB": "4.8",
      "avgFG3": "2.3",
      "avgBLK": "0.9",
      "avgSTL": "1.5",
      "avgTOV": "1.4",
      "MyRanking": "76",
      "Sleeper Rank": "77",
      "Discrepency": "1",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jalen Green",
      "avgFantasyScore": "19.98",
      "avgSingleGameHigh": "29.92",
      "avgTwoGameHigh": "27.46",
      "avgPTS": "14.1",
      "avgAST": "5.5",
      "avgTRB": "3.7",
      "avgFG3": "2.6",
      "avgBLK": "0.4",
      "avgSTL": "1.6",
      "avgTOV": "1.4",
      "MyRanking": "77",
      "Sleeper Rank": "88",
      "Discrepency": "11",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jordan Poole",
      "avgFantasyScore": "19.82",
      "avgSingleGameHigh": "31.75",
      "avgTwoGameHigh": "28.6",
      "avgPTS": "21",
      "avgAST": "3.4",
      "avgTRB": "4.6",
      "avgFG3": "2.9",
      "avgBLK": "0.3",
      "avgSTL": "0.9",
      "avgTOV": "2.5",
      "MyRanking": "78",
      "Sleeper Rank": "57",
      "Discrepency": "-21",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Coby White",
      "avgFantasyScore": "19.76",
      "avgSingleGameHigh": "29.82",
      "avgTwoGameHigh": "27.025",
      "avgPTS": "20.5",
      "avgAST": "4.5",
      "avgTRB": "3",
      "avgFG3": "3.5",
      "avgBLK": "0.4",
      "avgSTL": "1.3",
      "avgTOV": "3",
      "MyRanking": "79",
      "Sleeper Rank": "91",
      "Discrepency": "12",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Bobby Portis",
      "avgFantasyScore": "19.66",
      "avgSingleGameHigh": "33.93",
      "avgTwoGameHigh": "28.93",
      "avgPTS": "20.4",
      "avgAST": "4.5",
      "avgTRB": "3.7",
      "avgFG3": "2.9",
      "avgBLK": "0.2",
      "avgSTL": "0.9",
      "avgTOV": "2.4",
      "MyRanking": "80",
      "Sleeper Rank": "218",
      "Discrepency": "138",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Malik Monk",
      "avgFantasyScore": "19.66",
      "avgSingleGameHigh": "28.7",
      "avgTwoGameHigh": "25.625",
      "avgPTS": "13.9",
      "avgAST": "2.1",
      "avgTRB": "8.4",
      "avgFG3": "1.3",
      "avgBLK": "0.5",
      "avgSTL": "0.7",
      "avgTOV": "1.2",
      "MyRanking": "81",
      "Sleeper Rank": "99",
      "Discrepency": "18",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Cameron Johnson",
      "avgFantasyScore": "19.55",
      "avgSingleGameHigh": "26.5",
      "avgTwoGameHigh": "23.835",
      "avgPTS": "17.2",
      "avgAST": "5.6",
      "avgTRB": "3.8",
      "avgFG3": "2.1",
      "avgBLK": "0.6",
      "avgSTL": "0.9",
      "avgTOV": "2.4",
      "MyRanking": "82",
      "Sleeper Rank": "123",
      "Discrepency": "41",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Cam Thomas",
      "avgFantasyScore": "19.42",
      "avgSingleGameHigh": "30.75",
      "avgTwoGameHigh": "27.125",
      "avgPTS": "18.8",
      "avgAST": "3.4",
      "avgTRB": "4.3",
      "avgFG3": "2.8",
      "avgBLK": "0.4",
      "avgSTL": "0.9",
      "avgTOV": "1.7",
      "MyRanking": "83",
      "Sleeper Rank": "127",
      "Discrepency": "44",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Draymond Green",
      "avgFantasyScore": "19.33",
      "avgSingleGameHigh": "28.75",
      "avgTwoGameHigh": "26.425",
      "avgPTS": "24",
      "avgAST": "3.8",
      "avgTRB": "3.3",
      "avgFG3": "2.7",
      "avgBLK": "0.1",
      "avgSTL": "0.6",
      "avgTOV": "2.5",
      "MyRanking": "84",
      "Sleeper Rank": "201",
      "Discrepency": "117",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Andrew Wiggins",
      "avgFantasyScore": "19.28",
      "avgSingleGameHigh": "29.89",
      "avgTwoGameHigh": "26.72",
      "avgPTS": "9",
      "avgAST": "5.6",
      "avgTRB": "6.1",
      "avgFG3": "1.2",
      "avgBLK": "1",
      "avgSTL": "1.5",
      "avgTOV": "2.6",
      "MyRanking": "85",
      "Sleeper Rank": "144",
      "Discrepency": "59",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Lauri Markkanen",
      "avgFantasyScore": "19.19",
      "avgSingleGameHigh": "29",
      "avgTwoGameHigh": "26.18",
      "avgPTS": "18",
      "avgAST": "2.6",
      "avgTRB": "4.5",
      "avgFG3": "2.2",
      "avgBLK": "0.8",
      "avgSTL": "1",
      "avgTOV": "1.6",
      "MyRanking": "86",
      "Sleeper Rank": "47",
      "Discrepency": "-39",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Russell Westbrook",
      "avgFantasyScore": "19.09",
      "avgSingleGameHigh": "31.18",
      "avgTwoGameHigh": "27.25",
      "avgPTS": "19",
      "avgAST": "1.5",
      "avgTRB": "5.9",
      "avgFG3": "2.9",
      "avgBLK": "0.4",
      "avgSTL": "0.7",
      "avgTOV": "1.4",
      "MyRanking": "87",
      "Sleeper Rank": "228",
      "Discrepency": "141",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Kelly Oubre Jr.",
      "avgFantasyScore": "18.98",
      "avgSingleGameHigh": "26.06",
      "avgTwoGameHigh": "24.335",
      "avgPTS": "13.3",
      "avgAST": "6.1",
      "avgTRB": "4.9",
      "avgFG3": "1.3",
      "avgBLK": "0.5",
      "avgSTL": "1.4",
      "avgTOV": "3.2",
      "MyRanking": "88",
      "Sleeper Rank": "198",
      "Discrepency": "110",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Alexandre Sarr",
      "avgFantasyScore": "18.94",
      "avgSingleGameHigh": "28.6",
      "avgTwoGameHigh": "25.675",
      "avgPTS": "15.1",
      "avgAST": "1.8",
      "avgTRB": "6.1",
      "avgFG3": "1.2",
      "avgBLK": "0.5",
      "avgSTL": "1.5",
      "avgTOV": "1.3",
      "MyRanking": "89",
      "Sleeper Rank": "72",
      "Discrepency": "-17",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jalen Suggs",
      "avgFantasyScore": "18.79",
      "avgSingleGameHigh": "29.5",
      "avgTwoGameHigh": "27.15",
      "avgPTS": "13",
      "avgAST": "2.4",
      "avgTRB": "6.5",
      "avgFG3": "1.6",
      "avgBLK": "1.5",
      "avgSTL": "0.7",
      "avgTOV": "1.7",
      "MyRanking": "90",
      "Sleeper Rank": "71",
      "Discrepency": "-19",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Norman Powell",
      "avgFantasyScore": "18.61",
      "avgSingleGameHigh": "27.5",
      "avgTwoGameHigh": "24.945",
      "avgPTS": "16.2",
      "avgAST": "3.7",
      "avgTRB": "4",
      "avgFG3": "2.2",
      "avgBLK": "0.9",
      "avgSTL": "1.5",
      "avgTOV": "2.9",
      "MyRanking": "91",
      "Sleeper Rank": "142",
      "Discrepency": "51",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Anfernee Simons",
      "avgFantasyScore": "18.52",
      "avgSingleGameHigh": "26.5",
      "avgTwoGameHigh": "24.9",
      "avgPTS": "21.8",
      "avgAST": "2.1",
      "avgTRB": "3.2",
      "avgFG3": "3",
      "avgBLK": "0.1",
      "avgSTL": "1.2",
      "avgTOV": "1.8",
      "MyRanking": "92",
      "Sleeper Rank": "110",
      "Discrepency": "18",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Devin Vassell",
      "avgFantasyScore": "18.52",
      "avgSingleGameHigh": "26.05",
      "avgTwoGameHigh": "23.475",
      "avgPTS": "19.3",
      "avgAST": "4.8",
      "avgTRB": "2.7",
      "avgFG3": "3.1",
      "avgBLK": "0.1",
      "avgSTL": "0.9",
      "avgTOV": "2",
      "MyRanking": "93",
      "Sleeper Rank": "93",
      "Discrepency": "0",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Tari Eason",
      "avgFantasyScore": "18.5",
      "avgSingleGameHigh": "28.39",
      "avgTwoGameHigh": "24.97",
      "avgPTS": "16.3",
      "avgAST": "2.9",
      "avgTRB": "4",
      "avgFG3": "2.5",
      "avgBLK": "0.5",
      "avgSTL": "1.3",
      "avgTOV": "1.4",
      "MyRanking": "94",
      "Sleeper Rank": "54",
      "Discrepency": "-40",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Nicolas Claxton",
      "avgFantasyScore": "18.38",
      "avgSingleGameHigh": "28.35",
      "avgTwoGameHigh": "25.25",
      "avgPTS": "12",
      "avgAST": "1.5",
      "avgTRB": "6.4",
      "avgFG3": "1.1",
      "avgBLK": "0.9",
      "avgSTL": "1.7",
      "avgTOV": "1.1",
      "MyRanking": "95",
      "Sleeper Rank": "107",
      "Discrepency": "12",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Christian Braun",
      "avgFantasyScore": "18.2",
      "avgSingleGameHigh": "25.96",
      "avgTwoGameHigh": "23.875",
      "avgPTS": "10.3",
      "avgAST": "2.2",
      "avgTRB": "7.4",
      "avgFG3": "0.1",
      "avgBLK": "1.4",
      "avgSTL": "0.9",
      "avgTOV": "1.2",
      "MyRanking": "96",
      "Sleeper Rank": "131",
      "Discrepency": "35",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Brook Lopez",
      "avgFantasyScore": "18.13",
      "avgSingleGameHigh": "27.42",
      "avgTwoGameHigh": "25.665",
      "avgPTS": "15.4",
      "avgAST": "2.6",
      "avgTRB": "5.2",
      "avgFG3": "1.1",
      "avgBLK": "0.5",
      "avgSTL": "1.1",
      "avgTOV": "1",
      "MyRanking": "97",
      "Sleeper Rank": "282",
      "Discrepency": "185",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Tobias Harris",
      "avgFantasyScore": "18.12",
      "avgSingleGameHigh": "26.32",
      "avgTwoGameHigh": "24.07",
      "avgPTS": "13",
      "avgAST": "1.8",
      "avgTRB": "5",
      "avgFG3": "1.7",
      "avgBLK": "1.9",
      "avgSTL": "0.6",
      "avgTOV": "1.1",
      "MyRanking": "98",
      "Sleeper Rank": "164",
      "Discrepency": "66",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Keegan Murray",
      "avgFantasyScore": "18.09",
      "avgSingleGameHigh": "26.64",
      "avgTwoGameHigh": "24.615",
      "avgPTS": "13.7",
      "avgAST": "2.2",
      "avgTRB": "5.9",
      "avgFG3": "1.2",
      "avgBLK": "0.8",
      "avgSTL": "1",
      "avgTOV": "1.2",
      "MyRanking": "99",
      "Sleeper Rank": "94",
      "Discrepency": "-5",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Keyonte George",
      "avgFantasyScore": "18.07",
      "avgSingleGameHigh": "25.85",
      "avgTwoGameHigh": "24.225",
      "avgPTS": "12.4",
      "avgAST": "1.4",
      "avgTRB": "6.7",
      "avgFG3": "2",
      "avgBLK": "0.9",
      "avgSTL": "0.8",
      "avgTOV": "0.8",
      "MyRanking": "100",
      "Sleeper Rank": "151",
      "Discrepency": "51",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Santi Aldama",
      "avgFantasyScore": "18.01",
      "avgSingleGameHigh": "26.45",
      "avgTwoGameHigh": "25.05",
      "avgPTS": "16.8",
      "avgAST": "5.6",
      "avgTRB": "3.8",
      "avgFG3": "2.6",
      "avgBLK": "0.1",
      "avgSTL": "0.7",
      "avgTOV": "2.7",
      "MyRanking": "101",
      "Sleeper Rank": "150",
      "Discrepency": "49",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Mikal Bridges",
      "avgFantasyScore": "18",
      "avgSingleGameHigh": "26.54",
      "avgTwoGameHigh": "24.335",
      "avgPTS": "12.5",
      "avgAST": "2.9",
      "avgTRB": "6.4",
      "avgFG3": "1.8",
      "avgBLK": "0.4",
      "avgSTL": "0.8",
      "avgTOV": "1.1",
      "MyRanking": "102",
      "Sleeper Rank": "79",
      "Discrepency": "-23",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Bradley Beal",
      "avgFantasyScore": "17.89",
      "avgSingleGameHigh": "26.5",
      "avgTwoGameHigh": "25.03",
      "avgPTS": "17.6",
      "avgAST": "3.7",
      "avgTRB": "3.2",
      "avgFG3": "2",
      "avgBLK": "0.5",
      "avgSTL": "0.9",
      "avgTOV": "1.6",
      "MyRanking": "103",
      "Sleeper Rank": "186",
      "Discrepency": "83",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jaden McDaniels",
      "avgFantasyScore": "17.88",
      "avgSingleGameHigh": "25.96",
      "avgTwoGameHigh": "24.165",
      "avgPTS": "17",
      "avgAST": "3.7",
      "avgTRB": "3.3",
      "avgFG3": "1.9",
      "avgBLK": "0.5",
      "avgSTL": "1.1",
      "avgTOV": "1.9",
      "MyRanking": "104",
      "Sleeper Rank": "125",
      "Discrepency": "21",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Chris Paul",
      "avgFantasyScore": "17.87",
      "avgSingleGameHigh": "26.13",
      "avgTwoGameHigh": "24.375",
      "avgPTS": "12.2",
      "avgAST": "2",
      "avgTRB": "5.7",
      "avgFG3": "1.2",
      "avgBLK": "0.9",
      "avgSTL": "1.3",
      "avgTOV": "1.2",
      "MyRanking": "105",
      "Sleeper Rank": "329",
      "Discrepency": "224",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Daniel Gafford",
      "avgFantasyScore": "17.73",
      "avgSingleGameHigh": "27.22",
      "avgTwoGameHigh": "23.86",
      "avgPTS": "8.8",
      "avgAST": "7.4",
      "avgTRB": "3.6",
      "avgFG3": "1.7",
      "avgBLK": "0.3",
      "avgSTL": "1.3",
      "avgTOV": "1.6",
      "MyRanking": "106",
      "Sleeper Rank": "135",
      "Discrepency": "29",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Shaedon Sharpe",
      "avgFantasyScore": "17.67",
      "avgSingleGameHigh": "27.18",
      "avgTwoGameHigh": "25.025",
      "avgPTS": "12.3",
      "avgAST": "1.4",
      "avgTRB": "6.8",
      "avgFG3": "0",
      "avgBLK": "1.8",
      "avgSTL": "0.4",
      "avgTOV": "1.2",
      "MyRanking": "107",
      "Sleeper Rank": "101",
      "Discrepency": "-6",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jaden Ivey",
      "avgFantasyScore": "17.58",
      "avgSingleGameHigh": "24.6",
      "avgTwoGameHigh": "21.8",
      "avgPTS": "18.5",
      "avgAST": "2.8",
      "avgTRB": "4.5",
      "avgFG3": "2",
      "avgBLK": "0.2",
      "avgSTL": "0.9",
      "avgTOV": "2.1",
      "MyRanking": "108",
      "Sleeper Rank": "132",
      "Discrepency": "24",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Dereck Lively II",
      "avgFantasyScore": "17.53",
      "avgSingleGameHigh": "26",
      "avgTwoGameHigh": "22.125",
      "avgPTS": "17.6",
      "avgAST": "4",
      "avgTRB": "4.1",
      "avgFG3": "2.1",
      "avgBLK": "0.4",
      "avgSTL": "0.9",
      "avgTOV": "3",
      "MyRanking": "109",
      "Sleeper Rank": "56",
      "Discrepency": "-53",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Toumani Camara",
      "avgFantasyScore": "17.44",
      "avgSingleGameHigh": "24.5",
      "avgTwoGameHigh": "22.645",
      "avgPTS": "8.7",
      "avgAST": "2.4",
      "avgTRB": "7.5",
      "avgFG3": "0",
      "avgBLK": "1.6",
      "avgSTL": "0.6",
      "avgTOV": "1.1",
      "MyRanking": "110",
      "Sleeper Rank": "140",
      "Discrepency": "30",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Payton Pritchard",
      "avgFantasyScore": "17.22",
      "avgSingleGameHigh": "29.25",
      "avgTwoGameHigh": "25.645",
      "avgPTS": "11.3",
      "avgAST": "2.2",
      "avgTRB": "5.8",
      "avgFG3": "1.7",
      "avgBLK": "0.6",
      "avgSTL": "1.5",
      "avgTOV": "1.4",
      "MyRanking": "111",
      "Sleeper Rank": "129",
      "Discrepency": "18",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Bilal Coulibaly",
      "avgFantasyScore": "17.03",
      "avgSingleGameHigh": "26.94",
      "avgTwoGameHigh": "24.415",
      "avgPTS": "14.3",
      "avgAST": "3.5",
      "avgTRB": "3.8",
      "avgFG3": "3.2",
      "avgBLK": "0.2",
      "avgSTL": "0.9",
      "avgTOV": "1",
      "MyRanking": "112",
      "Sleeper Rank": "90",
      "Discrepency": "-22",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Yves Missi",
      "avgFantasyScore": "16.91",
      "avgSingleGameHigh": "24.5",
      "avgTwoGameHigh": "22.795",
      "avgPTS": "12.3",
      "avgAST": "3.4",
      "avgTRB": "5",
      "avgFG3": "1.1",
      "avgBLK": "0.7",
      "avgSTL": "1.3",
      "avgTOV": "2.1",
      "MyRanking": "113",
      "Sleeper Rank": "161",
      "Discrepency": "48",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Brandin Podziemski",
      "avgFantasyScore": "16.67",
      "avgSingleGameHigh": "26.4",
      "avgTwoGameHigh": "23.7",
      "avgPTS": "9.1",
      "avgAST": "1.4",
      "avgTRB": "8.2",
      "avgFG3": "0",
      "avgBLK": "1.3",
      "avgSTL": "0.5",
      "avgTOV": "1.1",
      "MyRanking": "114",
      "Sleeper Rank": "96",
      "Discrepency": "-18",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Clint Capela",
      "avgFantasyScore": "16.6",
      "avgSingleGameHigh": "24.25",
      "avgTwoGameHigh": "22.625",
      "avgPTS": "11.7",
      "avgAST": "3.4",
      "avgTRB": "5.1",
      "avgFG3": "1.8",
      "avgBLK": "0.2",
      "avgSTL": "1.1",
      "avgTOV": "1.2",
      "MyRanking": "115",
      "Sleeper Rank": "257",
      "Discrepency": "142",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Zach Edey",
      "avgFantasyScore": "16.56",
      "avgSingleGameHigh": "27.05",
      "avgTwoGameHigh": "24.675",
      "avgPTS": "8.9",
      "avgAST": "1.1",
      "avgTRB": "8.5",
      "avgFG3": "0",
      "avgBLK": "1",
      "avgSTL": "0.6",
      "avgTOV": "0.9",
      "MyRanking": "116",
      "Sleeper Rank": "89",
      "Discrepency": "-27",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Quentin Grimes",
      "avgFantasyScore": "16.51",
      "avgSingleGameHigh": "27.68",
      "avgTwoGameHigh": "24.635",
      "avgPTS": "9.2",
      "avgAST": "1",
      "avgTRB": "8.3",
      "avgFG3": "0.3",
      "avgBLK": "1.3",
      "avgSTL": "0.5",
      "avgTOV": "1.3",
      "MyRanking": "117",
      "Sleeper Rank": "143",
      "Discrepency": "26",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jabari Smith",
      "avgFantasyScore": "16.42",
      "avgSingleGameHigh": "25.22",
      "avgTwoGameHigh": "21.86",
      "avgPTS": "14.6",
      "avgAST": "3",
      "avgTRB": "4.3",
      "avgFG3": "2.2",
      "avgBLK": "0.3",
      "avgSTL": "1",
      "avgTOV": "1.9",
      "MyRanking": "118",
      "Sleeper Rank": "113",
      "Discrepency": "-5",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jrue Holiday",
      "avgFantasyScore": "16.31",
      "avgSingleGameHigh": "24.56",
      "avgTwoGameHigh": "22.695",
      "avgPTS": "12.2",
      "avgAST": "1.1",
      "avgTRB": "7",
      "avgFG3": "1.7",
      "avgBLK": "0.7",
      "avgSTL": "0.4",
      "avgTOV": "1.1",
      "MyRanking": "119",
      "Sleeper Rank": "162",
      "Discrepency": "43",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jerami Grant",
      "avgFantasyScore": "16.29",
      "avgSingleGameHigh": "23.86",
      "avgTwoGameHigh": "23.145",
      "avgPTS": "11.1",
      "avgAST": "3.9",
      "avgTRB": "4.3",
      "avgFG3": "1.7",
      "avgBLK": "0.4",
      "avgSTL": "1.1",
      "avgTOV": "1.2",
      "MyRanking": "120",
      "Sleeper Rank": "165",
      "Discrepency": "45",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Aaron Gordon",
      "avgFantasyScore": "16.21",
      "avgSingleGameHigh": "24.5",
      "avgTwoGameHigh": "22.815",
      "avgPTS": "14.4",
      "avgAST": "2.1",
      "avgTRB": "3.5",
      "avgFG3": "2.3",
      "avgBLK": "1",
      "avgSTL": "0.9",
      "avgTOV": "1.4",
      "MyRanking": "121",
      "Sleeper Rank": "148",
      "Discrepency": "27",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Benedect Mathurin",
      "avgFantasyScore": "16.13",
      "avgSingleGameHigh": "26",
      "avgTwoGameHigh": "23.475",
      "avgPTS": "14.7",
      "avgAST": "3.2",
      "avgTRB": "4.8",
      "avgFG3": "1.5",
      "avgBLK": "0.3",
      "avgSTL": "0.5",
      "avgTOV": "1.4",
      "MyRanking": "122",
      "Sleeper Rank": "146",
      "Discrepency": "24",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Ayo Dosunmu",
      "avgFantasyScore": "16.04",
      "avgSingleGameHigh": "25.29",
      "avgTwoGameHigh": "22.07",
      "avgPTS": "16.1",
      "avgAST": "1.9",
      "avgTRB": "5.3",
      "avgFG3": "1.4",
      "avgBLK": "0.3",
      "avgSTL": "0.7",
      "avgTOV": "1.9",
      "MyRanking": "123",
      "Sleeper Rank": "191",
      "Discrepency": "68",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Kel'el Ware",
      "avgFantasyScore": "16.03",
      "avgSingleGameHigh": "23.8",
      "avgTwoGameHigh": "21.85",
      "avgPTS": "12.3",
      "avgAST": "4.5",
      "avgTRB": "3.5",
      "avgFG3": "1.3",
      "avgBLK": "0.4",
      "avgSTL": "0.9",
      "avgTOV": "1.5",
      "MyRanking": "124",
      "Sleeper Rank": "75",
      "Discrepency": "-49",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Al Horford",
      "avgFantasyScore": "15.97",
      "avgSingleGameHigh": "23.78",
      "avgTwoGameHigh": "22.61",
      "avgPTS": "9.3",
      "avgAST": "0.9",
      "avgTRB": "7.4",
      "avgFG3": "0.5",
      "avgBLK": "1.1",
      "avgSTL": "0.6",
      "avgTOV": "0.9",
      "MyRanking": "125",
      "Sleeper Rank": "374",
      "Discrepency": "249",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Stephon Castle",
      "avgFantasyScore": "15.96",
      "avgSingleGameHigh": "23.71",
      "avgTwoGameHigh": "22.04",
      "avgPTS": "9",
      "avgAST": "2.1",
      "avgTRB": "6.2",
      "avgFG3": "1.9",
      "avgBLK": "0.8",
      "avgSTL": "0.6",
      "avgTOV": "0.8",
      "MyRanking": "126",
      "Sleeper Rank": "84",
      "Discrepency": "-42",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Ausar Thompson",
      "avgFantasyScore": "15.91",
      "avgSingleGameHigh": "24.28",
      "avgTwoGameHigh": "21.39",
      "avgPTS": "14.7",
      "avgAST": "4.1",
      "avgTRB": "3.7",
      "avgFG3": "1.2",
      "avgBLK": "0.3",
      "avgSTL": "0.9",
      "avgTOV": "2.2",
      "MyRanking": "127",
      "Sleeper Rank": "58",
      "Discrepency": "-69",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "DiVincenzo",
      "avgFantasyScore": "15.86",
      "avgSingleGameHigh": "24.28",
      "avgTwoGameHigh": "22.39",
      "avgPTS": "10.1",
      "avgAST": "2.3",
      "avgTRB": "5.1",
      "avgFG3": "0.2",
      "avgBLK": "0.7",
      "avgSTL": "1.7",
      "avgTOV": "1.4",
      "MyRanking": "128",
      "Sleeper Rank": "157",
      "Discrepency": "29",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Wendell Carter",
      "avgFantasyScore": "15.77",
      "avgSingleGameHigh": "25.3",
      "avgTwoGameHigh": "22.5",
      "avgPTS": "11.7",
      "avgAST": "3.6",
      "avgTRB": "3.7",
      "avgFG3": "2.8",
      "avgBLK": "0.3",
      "avgSTL": "1.2",
      "avgTOV": "1.6",
      "MyRanking": "129",
      "Sleeper Rank": "154",
      "Discrepency": "25",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Donovan Clingan",
      "avgFantasyScore": "15.72",
      "avgSingleGameHigh": "27.4",
      "avgTwoGameHigh": "23.975",
      "avgPTS": "9.1",
      "avgAST": "2",
      "avgTRB": "7.2",
      "avgFG3": "0.5",
      "avgBLK": "0.6",
      "avgSTL": "0.8",
      "avgTOV": "1.1",
      "MyRanking": "130",
      "Sleeper Rank": "70",
      "Discrepency": "-60",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Herb Jones",
      "avgFantasyScore": "15.68",
      "avgSingleGameHigh": "24.5",
      "avgTwoGameHigh": "21.915",
      "avgPTS": "6.5",
      "avgAST": "1.1",
      "avgTRB": "7.9",
      "avgFG3": "0.2",
      "avgBLK": "1.6",
      "avgSTL": "0.5",
      "avgTOV": "1.1",
      "MyRanking": "131",
      "Sleeper Rank": "120",
      "Discrepency": "-11",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Naji Marshall",
      "avgFantasyScore": "15.64",
      "avgSingleGameHigh": "24.7",
      "avgTwoGameHigh": "22.625",
      "avgPTS": "10.3",
      "avgAST": "3.3",
      "avgTRB": "3.9",
      "avgFG3": "1.1",
      "avgBLK": "0.5",
      "avgSTL": "1.9",
      "avgTOV": "1.8",
      "MyRanking": "132",
      "Sleeper Rank": "240",
      "Discrepency": "108",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Grant Williams",
      "avgFantasyScore": "15.59",
      "avgSingleGameHigh": "19.5",
      "avgTwoGameHigh": "18.25",
      "avgPTS": "13.2",
      "avgAST": "3",
      "avgTRB": "4.8",
      "avgFG3": "0.9",
      "avgBLK": "0.2",
      "avgSTL": "1",
      "avgTOV": "1.6",
      "MyRanking": "133",
      "Sleeper Rank": "331",
      "Discrepency": "198",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Goga Bitazde",
      "avgFantasyScore": "15.56",
      "avgSingleGameHigh": "24.3",
      "avgTwoGameHigh": "23",
      "avgPTS": "10.4",
      "avgAST": "2.3",
      "avgTRB": "5.1",
      "avgFG3": "1.7",
      "avgBLK": "0.8",
      "avgSTL": "1.1",
      "avgTOV": "1.8",
      "MyRanking": "134",
      "Sleeper Rank": "155",
      "Discrepency": "21",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Rui Hachimura",
      "avgFantasyScore": "15.43",
      "avgSingleGameHigh": "22.61",
      "avgTwoGameHigh": "20.86",
      "avgPTS": "7.2",
      "avgAST": "2",
      "avgTRB": "6.6",
      "avgFG3": "0",
      "avgBLK": "1.4",
      "avgSTL": "0.7",
      "avgTOV": "1",
      "MyRanking": "135",
      "Sleeper Rank": "166",
      "Discrepency": "31",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Mallik Beasley",
      "avgFantasyScore": "15.3",
      "avgSingleGameHigh": "22.96",
      "avgTwoGameHigh": "21.25",
      "avgPTS": "13.1",
      "avgAST": "1.4",
      "avgTRB": "5",
      "avgFG3": "1.7",
      "avgBLK": "0.4",
      "avgSTL": "0.8",
      "avgTOV": "0.8",
      "MyRanking": "136",
      "Sleeper Rank": "387",
      "Discrepency": "251",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Yabusele",
      "avgFantasyScore": "15.13",
      "avgSingleGameHigh": "24.45",
      "avgTwoGameHigh": "22.075",
      "avgPTS": "16.3",
      "avgAST": "1.7",
      "avgTRB": "2.6",
      "avgFG3": "3.9",
      "avgBLK": "0.1",
      "avgSTL": "0.9",
      "avgTOV": "1",
      "MyRanking": "137",
      "Sleeper Rank": "250",
      "Discrepency": "113",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Caris LeVert",
      "avgFantasyScore": "15.06",
      "avgSingleGameHigh": "24.85",
      "avgTwoGameHigh": "21.5",
      "avgPTS": "11",
      "avgAST": "2.1",
      "avgTRB": "5.6",
      "avgFG3": "1.5",
      "avgBLK": "0.3",
      "avgSTL": "0.8",
      "avgTOV": "1.2",
      "MyRanking": "138",
      "Sleeper Rank": "220",
      "Discrepency": "82",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Andrew Nembhard",
      "avgFantasyScore": "14.83",
      "avgSingleGameHigh": "22.55",
      "avgTwoGameHigh": "20.425",
      "avgPTS": "12.1",
      "avgAST": "3.4",
      "avgTRB": "3.2",
      "avgFG3": "1.7",
      "avgBLK": "0.5",
      "avgSTL": "0.9",
      "avgTOV": "1.2",
      "MyRanking": "139",
      "Sleeper Rank": "134",
      "Discrepency": "-5",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Lu Dort",
      "avgFantasyScore": "14.61",
      "avgSingleGameHigh": "23.91",
      "avgTwoGameHigh": "20.75",
      "avgPTS": "10",
      "avgAST": "5",
      "avgTRB": "3.3",
      "avgFG3": "0.8",
      "avgBLK": "0.2",
      "avgSTL": "1.2",
      "avgTOV": "1.7",
      "MyRanking": "140",
      "Sleeper Rank": "187",
      "Discrepency": "47",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Malcolm Brogdon",
      "avgFantasyScore": "14.56",
      "avgSingleGameHigh": "23.38",
      "avgTwoGameHigh": "20.315",
      "avgPTS": "10.1",
      "avgAST": "1.6",
      "avgTRB": "4.1",
      "avgFG3": "2.4",
      "avgBLK": "0.5",
      "avgSTL": "1.1",
      "avgTOV": "0.7",
      "MyRanking": "141",
      "Sleeper Rank": "391",
      "Discrepency": "250",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Bub Carrington",
      "avgFantasyScore": "14.53",
      "avgSingleGameHigh": "23",
      "avgTwoGameHigh": "20.98",
      "avgPTS": "12.7",
      "avgAST": "4.1",
      "avgTRB": "3.8",
      "avgFG3": "0.7",
      "avgBLK": "0.2",
      "avgSTL": "0.5",
      "avgTOV": "1.6",
      "MyRanking": "142",
      "Sleeper Rank": "133",
      "Discrepency": "-9",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Royce O'Neale",
      "avgFantasyScore": "14.39",
      "avgSingleGameHigh": "21.77",
      "avgTwoGameHigh": "20",
      "avgPTS": "9.8",
      "avgAST": "4.4",
      "avgTRB": "4.2",
      "avgFG3": "1.7",
      "avgBLK": "0.3",
      "avgSTL": "0.7",
      "avgTOV": "1.7",
      "MyRanking": "143",
      "Sleeper Rank": "230",
      "Discrepency": "87",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Gradey Dick",
      "avgFantasyScore": "14.25",
      "avgSingleGameHigh": "21",
      "avgTwoGameHigh": "19.815",
      "avgPTS": "9.1",
      "avgAST": "2.2",
      "avgTRB": "4.7",
      "avgFG3": "2.4",
      "avgBLK": "0.5",
      "avgSTL": "0.9",
      "avgTOV": "0.9",
      "MyRanking": "144",
      "Sleeper Rank": "174",
      "Discrepency": "30",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Spencer Dinwiddie",
      "avgFantasyScore": "14.25",
      "avgSingleGameHigh": "21.67",
      "avgTwoGameHigh": "20.02",
      "avgPTS": "14.4",
      "avgAST": "1.8",
      "avgTRB": "3.6",
      "avgFG3": "2.1",
      "avgBLK": "0.2",
      "avgSTL": "0.9",
      "avgTOV": "1.5",
      "MyRanking": "145",
      "Sleeper Rank": "269",
      "Discrepency": "124",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Lonzo Ball",
      "avgFantasyScore": "13.91",
      "avgSingleGameHigh": "20",
      "avgTwoGameHigh": "18.85",
      "avgPTS": "11",
      "avgAST": "4.4",
      "avgTRB": "2.6",
      "avgFG3": "1.4",
      "avgBLK": "0.2",
      "avgSTL": "0.9",
      "avgTOV": "1.3",
      "MyRanking": "146",
      "Sleeper Rank": "175",
      "Discrepency": "29",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Kevin Porter",
      "avgFantasyScore": "13.36",
      "avgSingleGameHigh": "23.91",
      "avgTwoGameHigh": "21.545",
      "avgPTS": "7.6",
      "avgAST": "3.3",
      "avgTRB": "3.4",
      "avgFG3": "1.9",
      "avgBLK": "0.5",
      "avgSTL": "1.3",
      "avgTOV": "1.2",
      "MyRanking": "147",
      "Sleeper Rank": "189",
      "Discrepency": "42",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jaime Jaquez Jr.",
      "avgFantasyScore": "12.39",
      "avgSingleGameHigh": "25.3",
      "avgTwoGameHigh": "20.525",
      "avgPTS": "10.3",
      "avgAST": "3.4",
      "avgTRB": "3.7",
      "avgFG3": "0.7",
      "avgBLK": "0.2",
      "avgSTL": "1.1",
      "avgTOV": "1.8",
      "MyRanking": "148",
      "Sleeper Rank": "180",
      "Discrepency": "32",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
  ];