export const playersList = [
    {
      "playerName": "Nikola Jokic",
      "playerUrl": "https://www.basketball-reference.com/players/j/jokicni01/gamelog/2025",
      "avgFantasyScore": "41.91",
      "avgSingleGameHigh": "48.63",
      "avgTwoGameHigh": "45.68",
      "avgPTS": "32.7",
      "avgAST": "6.4",
      "avgTRB": "5",
      "avgFG3": "2.1",
      "avgBLK": "1",
      "avgSTL": "1.7",
      "avgTOV": "2.4",
      "#": "1",
      "MyRanking": "1",
      "Sleeper Rank": "1",
      "Discrepency": "0",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Giannis Antetokounmpo",
      "playerUrl": "https://www.basketball-reference.com/players/a/antetgi01/gamelog/2025",
      "avgFantasyScore": "35.79",
      "avgSingleGameHigh": "42.74",
      "avgTwoGameHigh": "39.47",
      "avgPTS": "29.6",
      "avgAST": "10.2",
      "avgTRB": "12.7",
      "avgFG3": "2",
      "avgBLK": "0.6",
      "avgSTL": "1.8",
      "avgTOV": "3.3",
      "#": "2",
      "MyRanking": "2",
      "Sleeper Rank": "5",
      "Discrepency": "3",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Victor Wembanyama",
      "playerUrl": "https://www.basketball-reference.com/players/w/wembavi01/gamelog/2025",
      "avgFantasyScore": "35.76",
      "avgSingleGameHigh": "41.31",
      "avgTwoGameHigh": "38.47",
      "avgPTS": "24.3",
      "avgAST": "3.7",
      "avgTRB": "11",
      "avgFG3": "3.1",
      "avgBLK": "3.8",
      "avgSTL": "1.1",
      "avgTOV": "3.2",
      "#": "3",
      "MyRanking": "3",
      "Sleeper Rank": "2",
      "Discrepency": "-1",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Anthony Davis",
      "playerUrl": "https://www.basketball-reference.com/players/d/davisan02/gamelog/2025",
      "avgFantasyScore": "33",
      "avgSingleGameHigh": "40.27",
      "avgTwoGameHigh": "36.46",
      "avgPTS": "30.4",
      "avgAST": "6.5",
      "avgTRB": "11.9",
      "avgFG3": "0.2",
      "avgBLK": "1.2",
      "avgSTL": "0.9",
      "avgTOV": "3.1",
      "#": "4",
      "MyRanking": "6",
      "Sleeper Rank": "10",
      "Discrepency": "4",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Shai Gilgeous-Alexander",
      "playerUrl": "https://www.basketball-reference.com/players/g/gilgesh01/gamelog/2025",
      "avgFantasyScore": "32.2",
      "avgSingleGameHigh": "38.6",
      "avgTwoGameHigh": "35.46",
      "avgPTS": "24.7",
      "avgAST": "3.5",
      "avgTRB": "11.6",
      "avgFG3": "0.7",
      "avgBLK": "2.2",
      "avgSTL": "1.2",
      "avgTOV": "2.2",
      "#": "5",
      "MyRanking": "4",
      "Sleeper Rank": "4",
      "Discrepency": "0",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Luka Doncic",
      "playerUrl": "https://www.basketball-reference.com/players/d/doncilu01/gamelog/2025",
      "avgFantasyScore": "33.15",
      "avgSingleGameHigh": "37.42",
      "avgTwoGameHigh": "35.72",
      "avgPTS": "28.2",
      "avgAST": "7.7",
      "avgTRB": "8.2",
      "avgFG3": "3.5",
      "avgBLK": "0.4",
      "avgSTL": "1.8",
      "avgTOV": "3.6",
      "#": "6",
      "MyRanking": "5",
      "Sleeper Rank": "3",
      "Discrepency": "-2",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Karl-Anthony Towns",
      "playerUrl": "https://www.basketball-reference.com/players/t/townska01/gamelog/2025",
      "avgFantasyScore": "30.69",
      "avgSingleGameHigh": "36.75",
      "avgTwoGameHigh": "33.19",
      "avgPTS": "19.1",
      "avgAST": "6",
      "avgTRB": "13.9",
      "avgFG3": "0.9",
      "avgBLK": "0.4",
      "avgSTL": "0.7",
      "avgTOV": "2.9",
      "#": "7",
      "MyRanking": "7",
      "Sleeper Rank": "16",
      "Discrepency": "9",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Domantas Sabonis",
      "playerUrl": "https://www.basketball-reference.com/players/s/sabondo01/gamelog/2025",
      "avgFantasyScore": "30.19",
      "avgSingleGameHigh": "35",
      "avgTwoGameHigh": "31.36",
      "avgPTS": "26.3",
      "avgAST": "6.1",
      "avgTRB": "3.3",
      "avgFG3": "3.1",
      "avgBLK": "0.4",
      "avgSTL": "1.8",
      "avgTOV": "2.4",
      "#": "8",
      "MyRanking": "8",
      "Sleeper Rank": "11",
      "Discrepency": "3",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "LeBron James",
      "playerUrl": "https://www.basketball-reference.com/players/j/jamesle01/gamelog/2025",
      "avgFantasyScore": "29.32",
      "avgSingleGameHigh": "34.86",
      "avgTwoGameHigh": "31.92",
      "avgPTS": "25.9",
      "avgAST": "4.8",
      "avgTRB": "7.5",
      "avgFG3": "1.9",
      "avgBLK": "0.6",
      "avgSTL": "0.8",
      "avgTOV": "3",
      "#": "9",
      "MyRanking": "9",
      "Sleeper Rank": "15",
      "Discrepency": "6",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Cade Cunningham",
      "playerUrl": "https://www.basketball-reference.com/players/c/cunnica01/gamelog/2025",
      "avgFantasyScore": "29.02",
      "avgSingleGameHigh": "34.44",
      "avgTwoGameHigh": "32.49",
      "avgPTS": "24.4",
      "avgAST": "3.1",
      "avgTRB": "12.8",
      "avgFG3": "2",
      "avgBLK": "0.7",
      "avgSTL": "1",
      "avgTOV": "2.7",
      "#": "10",
      "MyRanking": "10",
      "Sleeper Rank": "7",
      "Discrepency": "-3",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Trae Young",
      "playerUrl": "https://www.basketball-reference.com/players/y/youngtr01/gamelog/2025",
      "avgFantasyScore": "26.97",
      "avgSingleGameHigh": "33.98",
      "avgTwoGameHigh": "30.8",
      "avgPTS": "24.4",
      "avgAST": "8.2",
      "avgTRB": "7.8",
      "avgFG3": "2.1",
      "avgBLK": "0.6",
      "avgSTL": "1",
      "avgTOV": "3.7",
      "#": "11",
      "MyRanking": "11",
      "Sleeper Rank": "21",
      "Discrepency": "10",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "LaMelo Ball",
      "playerUrl": "https://www.basketball-reference.com/players/b/ballla01/gamelog/2025",
      "avgFantasyScore": "26.46",
      "avgSingleGameHigh": "33.53",
      "avgTwoGameHigh": "29.39",
      "avgPTS": "22.8",
      "avgAST": "8.7",
      "avgTRB": "5.8",
      "avgFG3": "3",
      "avgBLK": "0.7",
      "avgSTL": "1.5",
      "avgTOV": "4.3",
      "#": "12",
      "MyRanking": "12",
      "Sleeper Rank": "20",
      "Discrepency": "8",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Ivica Zubac",
      "playerUrl": "https://www.basketball-reference.com/players/z/zubaciv01/gamelog/2025",
      "avgFantasyScore": "26.46",
      "avgSingleGameHigh": "33.44",
      "avgTwoGameHigh": "29.78",
      "avgPTS": "24.5",
      "avgAST": "6",
      "avgTRB": "4.4",
      "avgFG3": "4.4",
      "avgBLK": "0.4",
      "avgSTL": "1.1",
      "avgTOV": "2.9",
      "#": "13",
      "MyRanking": "13",
      "Sleeper Rank": "46",
      "Discrepency": "33",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "James Harden",
      "playerUrl": "https://www.basketball-reference.com/players/h/hardeja01/gamelog/2025",
      "avgFantasyScore": "28.02",
      "avgSingleGameHigh": "33.33",
      "avgTwoGameHigh": "30.11",
      "avgPTS": "24.2",
      "avgAST": "11.6",
      "avgTRB": "3.1",
      "avgFG3": "2.9",
      "avgBLK": "0.2",
      "avgSTL": "1.2",
      "avgTOV": "4.7",
      "#": "14",
      "MyRanking": "14",
      "Sleeper Rank": "44",
      "Discrepency": "30",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Paolo Banchero",
      "playerUrl": "https://www.basketball-reference.com/players/b/banchpa01/gamelog/2025",
      "avgFantasyScore": "26.39",
      "avgSingleGameHigh": "32.91",
      "avgTwoGameHigh": "29.58",
      "avgPTS": "26.6",
      "avgAST": "4.2",
      "avgTRB": "6",
      "avgFG3": "2.6",
      "avgBLK": "1.2",
      "avgSTL": "0.8",
      "avgTOV": "3.1",
      "#": "15",
      "MyRanking": "15",
      "Sleeper Rank": "6",
      "Discrepency": "-9",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Alperen Sengün",
      "playerUrl": "https://www.basketball-reference.com/players/s/sengual01/gamelog/2025",
      "avgFantasyScore": "26.83",
      "avgSingleGameHigh": "32.52",
      "avgTwoGameHigh": "30.01",
      "avgPTS": "19.1",
      "avgAST": "4.9",
      "avgTRB": "10.3",
      "avgFG3": "0.3",
      "avgBLK": "0.8",
      "avgSTL": "1.1",
      "avgTOV": "2.6",
      "#": "16",
      "MyRanking": "16",
      "Sleeper Rank": "24",
      "Discrepency": "8",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jalen Johnson",
      "playerUrl": "https://www.basketball-reference.com/players/j/johnsja05/gamelog/2025",
      "avgFantasyScore": "27.81",
      "avgSingleGameHigh": "32.35",
      "avgTwoGameHigh": "29.42",
      "avgPTS": "25.2",
      "avgAST": "7.4",
      "avgTRB": "4.9",
      "avgFG3": "3.8",
      "avgBLK": "0.3",
      "avgSTL": "1.1",
      "avgTOV": "3.6",
      "#": "17",
      "MyRanking": "17",
      "Sleeper Rank": "18",
      "Discrepency": "1",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Anthony Edwards",
      "playerUrl": "https://www.basketball-reference.com/players/e/edwaran01/gamelog/2025/",
      "avgFantasyScore": "26.8",
      "avgSingleGameHigh": "32.25",
      "avgTwoGameHigh": "29.78",
      "avgPTS": "26.1",
      "avgAST": "9.1",
      "avgTRB": "6.1",
      "avgFG3": "2.1",
      "avgBLK": "0.8",
      "avgSTL": "1",
      "avgTOV": "4.4",
      "#": "18",
      "MyRanking": "18",
      "Sleeper Rank": "8",
      "Discrepency": "-10",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Bam Adebayo",
      "playerUrl": "https://www.basketball-reference.com/players/a/adebaba01/gamelog/2025/",
      "avgFantasyScore": "25.78",
      "avgSingleGameHigh": "32.16",
      "avgTwoGameHigh": "28.98",
      "avgPTS": "19.3",
      "avgAST": "5.8",
      "avgTRB": "7.7",
      "avgFG3": "1.2",
      "avgBLK": "1",
      "avgSTL": "1.4",
      "avgTOV": "2.8",
      "#": "19",
      "MyRanking": "19",
      "Sleeper Rank": "38",
      "Discrepency": "19",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Josh Hart",
      "playerUrl": "https://www.basketball-reference.com/players/h/hartjo01/gamelog/2025/",
      "avgFantasyScore": "25.12",
      "avgSingleGameHigh": "32.02",
      "avgTwoGameHigh": "28.86",
      "avgPTS": "24.7",
      "avgAST": "4.6",
      "avgTRB": "4.8",
      "avgFG3": "2.9",
      "avgBLK": "0.5",
      "avgSTL": "1.3",
      "avgTOV": "2.2",
      "#": "20",
      "MyRanking": "20",
      "Sleeper Rank": "112",
      "Discrepency": "92",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Tyrese Maxey",
      "playerUrl": "https://www.basketball-reference.com/players/m/maxeyty01/gamelog/2025",
      "avgFantasyScore": "26.37",
      "avgSingleGameHigh": "31.97",
      "avgTwoGameHigh": "29.51",
      "avgPTS": "26",
      "avgAST": "7.3",
      "avgTRB": "2.9",
      "avgFG3": "2.3",
      "avgBLK": "0.1",
      "avgSTL": "0.9",
      "avgTOV": "2.5",
      "#": "21",
      "MyRanking": "21",
      "Sleeper Rank": "19",
      "Discrepency": "-2",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Josh Giddey",
      "playerUrl": "https://www.basketball-reference.com/players/g/giddejo01/gamelog/2025/",
      "avgFantasyScore": "24.65",
      "avgSingleGameHigh": "31.9",
      "avgTwoGameHigh": "29.07",
      "avgPTS": "16.8",
      "avgAST": "2.7",
      "avgTRB": "12.6",
      "avgFG3": "0",
      "avgBLK": "1.1",
      "avgSTL": "0.7",
      "avgTOV": "1.6",
      "#": "22",
      "MyRanking": "22",
      "Sleeper Rank": "36",
      "Discrepency": "14",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Evan Mobley",
      "playerUrl": "https://www.basketball-reference.com/players/m/mobleev01/gamelog/2025/",
      "avgFantasyScore": "25.74",
      "avgSingleGameHigh": "31.26",
      "avgTwoGameHigh": "28",
      "avgPTS": "13.6",
      "avgAST": "5.9",
      "avgTRB": "9.6",
      "avgFG3": "1.1",
      "avgBLK": "0.4",
      "avgSTL": "1.5",
      "avgTOV": "2.1",
      "#": "23",
      "MyRanking": "23",
      "Sleeper Rank": "14",
      "Discrepency": "-9",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Nikola Vucevic",
      "playerUrl": "https://www.basketball-reference.com/players/v/vucevni01/gamelog/2025/",
      "avgFantasyScore": "25.79",
      "avgSingleGameHigh": "31.17",
      "avgTwoGameHigh": "28.97",
      "avgPTS": "24",
      "avgAST": "5",
      "avgTRB": "4.5",
      "avgFG3": "3.3",
      "avgBLK": "0.2",
      "avgSTL": "1.3",
      "avgTOV": "2.1",
      "#": "24",
      "MyRanking": "24",
      "Sleeper Rank": "106",
      "Discrepency": "82",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Dejounte Murray",
      "playerUrl": "https://www.basketball-reference.com/players/m/murrade01/gamelog/2025/",
      "avgFantasyScore": "25.1",
      "avgSingleGameHigh": "31.17",
      "avgTwoGameHigh": "27.32",
      "avgPTS": "18.5",
      "avgAST": "3.5",
      "avgTRB": "10.1",
      "avgFG3": "1.8",
      "avgBLK": "0.7",
      "avgSTL": "0.8",
      "avgTOV": "1.6",
      "#": "25",
      "MyRanking": "25",
      "Sleeper Rank": "78",
      "Discrepency": "53",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Devin Booker",
      "playerUrl": "https://www.basketball-reference.com/players/b/bookede01/gamelog/2025/",
      "avgFantasyScore": "24.73",
      "avgSingleGameHigh": "31.1",
      "avgTwoGameHigh": "28.39",
      "avgPTS": "18.9",
      "avgAST": "5",
      "avgTRB": "10",
      "avgFG3": "1.2",
      "avgBLK": "1",
      "avgSTL": "1.6",
      "avgTOV": "2.9",
      "#": "26",
      "MyRanking": "26",
      "Sleeper Rank": "22",
      "Discrepency": "-4",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Kevin Durant",
      "playerUrl": "https://www.basketball-reference.com/players/d/duranke01/gamelog/2025",
      "avgFantasyScore": "26.02",
      "avgSingleGameHigh": "30.8",
      "avgTwoGameHigh": "28.69",
      "avgPTS": "22.2",
      "avgAST": "4.5",
      "avgTRB": "5.8",
      "avgFG3": "1.8",
      "avgBLK": "0.3",
      "avgSTL": "1.2",
      "avgTOV": "2.6",
      "#": "27",
      "MyRanking": "27",
      "Sleeper Rank": "28",
      "Discrepency": "1",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Tyler Herro",
      "playerUrl": "https://www.basketball-reference.com/players/h/herroty01/gamelog/2025/",
      "avgFantasyScore": "24.05",
      "avgSingleGameHigh": "30.8",
      "avgTwoGameHigh": "27.32",
      "avgPTS": "25.6",
      "avgAST": "7.1",
      "avgTRB": "4.1",
      "avgFG3": "2.4",
      "avgBLK": "0.2",
      "avgSTL": "0.9",
      "avgTOV": "2.9",
      "#": "28",
      "MyRanking": "28",
      "Sleeper Rank": "39",
      "Discrepency": "11",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jalen Williams",
      "playerUrl": "https://www.basketball-reference.com/players/w/willija06/gamelog/2025/",
      "avgFantasyScore": "24.62",
      "avgSingleGameHigh": "30.21",
      "avgTwoGameHigh": "27.24",
      "avgPTS": "12",
      "avgAST": "1.8",
      "avgTRB": "10.9",
      "avgFG3": "0",
      "avgBLK": "1.4",
      "avgSTL": "0.8",
      "avgTOV": "1.2",
      "#": "29",
      "MyRanking": "29",
      "Sleeper Rank": "37",
      "Discrepency": "8",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Stephen Curry",
      "playerUrl": "https://www.basketball-reference.com/players/c/curryst01/gamelog/2025",
      "avgFantasyScore": "25.41",
      "avgSingleGameHigh": "30.18",
      "avgTwoGameHigh": "27.71",
      "avgPTS": "27.6",
      "avgAST": "4.5",
      "avgTRB": "5.7",
      "avgFG3": "4.1",
      "avgBLK": "0.6",
      "avgSTL": "1.2",
      "avgTOV": "3.2",
      "#": "30",
      "MyRanking": "30",
      "Sleeper Rank": "13",
      "Discrepency": "-17",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Scottie Barnes",
      "playerUrl": "https://www.basketball-reference.com/players/b/barnesc01/gamelog/2025",
      "avgFantasyScore": "26.12",
      "avgSingleGameHigh": "30.06",
      "avgTwoGameHigh": "28.26",
      "avgPTS": "18.5",
      "avgAST": "3.2",
      "avgTRB": "9.3",
      "avgFG3": "1.2",
      "avgBLK": "1.6",
      "avgSTL": "0.9",
      "avgTOV": "2",
      "#": "31",
      "MyRanking": "31",
      "Sleeper Rank": "17",
      "Discrepency": "-14",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Walker Kessler",
      "playerUrl": "https://www.basketball-reference.com/players/k/kesslwa01/gamelog/2025/",
      "avgFantasyScore": "24.44",
      "avgSingleGameHigh": "30.02",
      "avgTwoGameHigh": "27.08",
      "avgPTS": "14.6",
      "avgAST": "7.2",
      "avgTRB": "8.1",
      "avgFG3": "1.5",
      "avgBLK": "0.6",
      "avgSTL": "1.2",
      "avgTOV": "2.9",
      "#": "32",
      "MyRanking": "32",
      "Sleeper Rank": "55",
      "Discrepency": "23",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "De'Aaron Fox",
      "playerUrl": "https://www.basketball-reference.com/players/f/foxde01/gamelog/2025/",
      "avgFantasyScore": "24.99",
      "avgSingleGameHigh": "29.41",
      "avgTwoGameHigh": "27.59",
      "avgPTS": "18.1",
      "avgAST": "4.3",
      "avgTRB": "9.6",
      "avgFG3": "1",
      "avgBLK": "0.7",
      "avgSTL": "1.3",
      "avgTOV": "2.1",
      "#": "33",
      "MyRanking": "33",
      "Sleeper Rank": "29",
      "Discrepency": "-4",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jamal Murray",
      "playerUrl": "https://www.basketball-reference.com/players/m/murraja01/gamelog/2025/",
      "avgFantasyScore": "23.57",
      "avgSingleGameHigh": "29.4",
      "avgTwoGameHigh": "26.63",
      "avgPTS": "23.5",
      "avgAST": "6.3",
      "avgTRB": "4.8",
      "avgFG3": "1.9",
      "avgBLK": "0.4",
      "avgSTL": "1.5",
      "avgTOV": "2.8",
      "#": "34",
      "MyRanking": "34",
      "Sleeper Rank": "41",
      "Discrepency": "7",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Kyrie Irving",
      "playerUrl": "https://www.basketball-reference.com/players/i/irvinky01/gamelog/2025",
      "avgFantasyScore": "24.66",
      "avgSingleGameHigh": "29.26",
      "avgTwoGameHigh": "27.28",
      "avgPTS": "21.5",
      "avgAST": "3.1",
      "avgTRB": "5.9",
      "avgFG3": "2.1",
      "avgBLK": "0.5",
      "avgSTL": "1.6",
      "avgTOV": "1.9",
      "#": "35",
      "MyRanking": "35",
      "Sleeper Rank": "52",
      "Discrepency": "17",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jalen Brunson",
      "playerUrl": "https://www.basketball-reference.com/players/b/brunsja01/gamelog/2025",
      "avgFantasyScore": "24.23",
      "avgSingleGameHigh": "29.02",
      "avgTwoGameHigh": "26.42",
      "avgPTS": "21.6",
      "avgAST": "5.1",
      "avgTRB": "5.3",
      "avgFG3": "1.8",
      "avgBLK": "0.7",
      "avgSTL": "1.6",
      "avgTOV": "2.2",
      "#": "36",
      "MyRanking": "36",
      "Sleeper Rank": "27",
      "Discrepency": "-9",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Desmond Bane",
      "playerUrl": "https://www.basketball-reference.com/players/b/banede01/gamelog/2025/",
      "avgFantasyScore": "23.08",
      "avgSingleGameHigh": "28.98",
      "avgTwoGameHigh": "25.83",
      "avgPTS": "22.2",
      "avgAST": "2",
      "avgTRB": "5.6",
      "avgFG3": "2",
      "avgBLK": "1.5",
      "avgSTL": "1.2",
      "avgTOV": "2.1",
      "#": "37",
      "MyRanking": "37",
      "Sleeper Rank": "49",
      "Discrepency": "12",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Donovan Mitchell",
      "playerUrl": "https://www.basketball-reference.com/players/m/mitchdo01/gamelog/2025",
      "avgFantasyScore": "24.31",
      "avgSingleGameHigh": "28.88",
      "avgTwoGameHigh": "27.17",
      "avgPTS": "24.1",
      "avgAST": "4.7",
      "avgTRB": "5.7",
      "avgFG3": "1.7",
      "avgBLK": "0.3",
      "avgSTL": "1.3",
      "avgTOV": "2.3",
      "#": "38",
      "MyRanking": "38",
      "Sleeper Rank": "31",
      "Discrepency": "-7",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jarrett Allen",
      "playerUrl": "https://www.basketball-reference.com/players/a/allenja01/gamelog/2025/",
      "avgFantasyScore": "21.35",
      "avgSingleGameHigh": "28.88",
      "avgTwoGameHigh": "25.61",
      "avgPTS": "20.2",
      "avgAST": "5.8",
      "avgTRB": "4.5",
      "avgFG3": "2.7",
      "avgBLK": "0.3",
      "avgSTL": "1.1",
      "avgTOV": "2.4",
      "#": "39",
      "MyRanking": "39",
      "Sleeper Rank": "66",
      "Discrepency": "27",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Amen Thompson",
      "playerUrl": "https://www.basketball-reference.com/players/t/thompam01/gamelog/2025/",
      "avgFantasyScore": "22.96",
      "avgSingleGameHigh": "28.83",
      "avgTwoGameHigh": "25.6",
      "avgPTS": "14.5",
      "avgAST": "2.8",
      "avgTRB": "9.6",
      "avgFG3": "0",
      "avgBLK": "1.2",
      "avgSTL": "1.2",
      "avgTOV": "1.9",
      "#": "40",
      "MyRanking": "40",
      "Sleeper Rank": "25",
      "Discrepency": "-15",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jaren Jackson Jr.",
      "playerUrl": "https://www.basketball-reference.com/players/j/jacksja02/gamelog/2025/",
      "avgFantasyScore": "23.29",
      "avgSingleGameHigh": "28.8",
      "avgTwoGameHigh": "26.1",
      "avgPTS": "17.5",
      "avgAST": "5.4",
      "avgTRB": "5.4",
      "avgFG3": "0.6",
      "avgBLK": "0.3",
      "avgSTL": "1.4",
      "avgTOV": "1.3",
      "#": "41",
      "MyRanking": "41",
      "Sleeper Rank": "23",
      "Discrepency": "-18",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Miles Bridges",
      "playerUrl": "https://www.basketball-reference.com/players/b/bridgmi02/gamelog/2025/",
      "avgFantasyScore": "23.57",
      "avgSingleGameHigh": "28.74",
      "avgTwoGameHigh": "26.51",
      "avgPTS": "17.5",
      "avgAST": "7.4",
      "avgTRB": "6.5",
      "avgFG3": "1.7",
      "avgBLK": "0.4",
      "avgSTL": "2",
      "avgTOV": "3.4",
      "#": "42",
      "MyRanking": "42",
      "Sleeper Rank": "87",
      "Discrepency": "45",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Rudy Gobert",
      "playerUrl": "https://www.basketball-reference.com/players/g/goberru01/gamelog/2025/",
      "avgFantasyScore": "22.39",
      "avgSingleGameHigh": "28.67",
      "avgTwoGameHigh": "26.01",
      "avgPTS": "14.1",
      "avgAST": "3.8",
      "avgTRB": "8.2",
      "avgFG3": "0.4",
      "avgBLK": "1.3",
      "avgSTL": "1.4",
      "avgTOV": "2",
      "#": "43",
      "MyRanking": "43",
      "Sleeper Rank": "117",
      "Discrepency": "74",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jalen Duren",
      "playerUrl": "https://www.basketball-reference.com/players/d/durenja01/gamelog/2025/",
      "avgFantasyScore": "21.36",
      "avgSingleGameHigh": "28.65",
      "avgTwoGameHigh": "25.51",
      "avgPTS": "20.6",
      "avgAST": "6.7",
      "avgTRB": "2.9",
      "avgFG3": "2.8",
      "avgBLK": "0.1",
      "avgSTL": "1.2",
      "avgTOV": "2.5",
      "#": "44",
      "MyRanking": "44",
      "Sleeper Rank": "68",
      "Discrepency": "24",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Ja Morant",
      "playerUrl": "https://www.basketball-reference.com/players/m/moranja01/gamelog/2025/",
      "avgFantasyScore": "23.39",
      "avgSingleGameHigh": "28.5",
      "avgTwoGameHigh": "25.54",
      "avgPTS": "23.2",
      "avgAST": "7.3",
      "avgTRB": "4.1",
      "avgFG3": "1.8",
      "avgBLK": "0.2",
      "avgSTL": "1.2",
      "avgTOV": "3.7",
      "#": "45",
      "MyRanking": "45",
      "Sleeper Rank": "51",
      "Discrepency": "6",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jimmy Butler",
      "playerUrl": "https://www.basketball-reference.com/players/b/butleji01/gamelog/2025/",
      "avgFantasyScore": "22.13",
      "avgSingleGameHigh": "28.48",
      "avgTwoGameHigh": "24.4",
      "avgPTS": "18",
      "avgAST": "2.2",
      "avgTRB": "4.8",
      "avgFG3": "2.3",
      "avgBLK": "0.9",
      "avgSTL": "1.5",
      "avgTOV": "1.4",
      "#": "46",
      "MyRanking": "46",
      "Sleeper Rank": "95",
      "Discrepency": "49",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Austin Reaves",
      "playerUrl": "https://www.basketball-reference.com/players/r/reaveau01/gamelog/2025/",
      "avgFantasyScore": "22.31",
      "avgSingleGameHigh": "28.46",
      "avgTwoGameHigh": "25.17",
      "avgPTS": "21.1",
      "avgAST": "5.4",
      "avgTRB": "6.3",
      "avgFG3": "1.8",
      "avgBLK": "0.3",
      "avgSTL": "0.8",
      "avgTOV": "2.8",
      "#": "47",
      "MyRanking": "47",
      "Sleeper Rank": "43",
      "Discrepency": "-4",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Chet Holmgren",
      "playerUrl": "https://www.basketball-reference.com/players/h/holmgch01/gamelog/2025/",
      "avgFantasyScore": "22.64",
      "avgSingleGameHigh": "28.38",
      "avgTwoGameHigh": "24.73",
      "avgPTS": "14.1",
      "avgAST": "4.4",
      "avgTRB": "5.9",
      "avgFG3": "1.1",
      "avgBLK": "0.7",
      "avgSTL": "3",
      "avgTOV": "2",
      "#": "38",
      "MyRanking": "38",
      "Sleeper Rank": "40",
      "Discrepency": "2",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Franz Wagner",
      "playerUrl": "https://www.basketball-reference.com/players/w/wagnefr01/gamelog/2025/",
      "avgFantasyScore": "24.32",
      "avgSingleGameHigh": "28.24",
      "avgTwoGameHigh": "26.85",
      "avgPTS": "16.9",
      "avgAST": "3.9",
      "avgTRB": "7.3",
      "avgFG3": "1.7",
      "avgBLK": "0.5",
      "avgSTL": "1",
      "avgTOV": "2.7",
      "#": "49",
      "MyRanking": "49",
      "Sleeper Rank": "26",
      "Discrepency": "-23",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Dyson Daniels",
      "playerUrl": "https://www.basketball-reference.com/players/d/daniedy01/gamelog/2025/",
      "avgFantasyScore": "23.43",
      "avgSingleGameHigh": "28.24",
      "avgTwoGameHigh": "25.79",
      "avgPTS": "23.9",
      "avgAST": "5.5",
      "avgTRB": "5.2",
      "avgFG3": "3.3",
      "avgBLK": "0.2",
      "avgSTL": "0.9",
      "avgTOV": "2.6",
      "#": "50",
      "MyRanking": "50",
      "Sleeper Rank": "48",
      "Discrepency": "-2",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Pascal Siakam",
      "playerUrl": "https://www.basketball-reference.com/players/s/siakapa01/gamelog/2025/",
      "avgFantasyScore": "22.83",
      "avgSingleGameHigh": "28.15",
      "avgTwoGameHigh": "25.86",
      "avgPTS": "20.3",
      "avgAST": "3.9",
      "avgTRB": "7.5",
      "avgFG3": "2.2",
      "avgBLK": "0.7",
      "avgSTL": "0.7",
      "avgTOV": "2.1",
      "#": "51",
      "MyRanking": "51",
      "Sleeper Rank": "62",
      "Discrepency": "11",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "CJ McCollum",
      "playerUrl": "https://www.basketball-reference.com/players/m/mccolcj01/gamelog/2025/",
      "avgFantasyScore": "20.64",
      "avgSingleGameHigh": "28.02",
      "avgTwoGameHigh": "23.28",
      "avgPTS": "21",
      "avgAST": "3.6",
      "avgTRB": "4.9",
      "avgFG3": "3.9",
      "avgBLK": "0.7",
      "avgSTL": "1.1",
      "avgTOV": "2.8",
      "#": "52",
      "MyRanking": "52",
      "Sleeper Rank": "158",
      "Discrepency": "106",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Deandre Ayton",
      "playerUrl": "https://www.basketball-reference.com/players/a/aytonde01/gamelog/2025/",
      "avgFantasyScore": "21.3",
      "avgSingleGameHigh": "27.96",
      "avgTwoGameHigh": "25.1",
      "avgPTS": "21.2",
      "avgAST": "3.5",
      "avgTRB": "5.1",
      "avgFG3": "3",
      "avgBLK": "0.7",
      "avgSTL": "1.1",
      "avgTOV": "1.9",
      "#": "53",
      "MyRanking": "53",
      "Sleeper Rank": "128",
      "Discrepency": "75",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Isaiah Hartenstein",
      "playerUrl": "https://www.basketball-reference.com/players/h/harteis01/gamelog/2025/",
      "avgFantasyScore": "22.78",
      "avgSingleGameHigh": "27.52",
      "avgTwoGameHigh": "25.36",
      "avgPTS": "16.4",
      "avgAST": "4.8",
      "avgTRB": "4.5",
      "avgFG3": "3.5",
      "avgBLK": "1.1",
      "avgSTL": "0.9",
      "avgTOV": "1.7",
      "#": "54",
      "MyRanking": "54",
      "Sleeper Rank": "74",
      "Discrepency": "20",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Brandon Ingram",
      "playerUrl": "https://www.basketball-reference.com/players/i/ingrabr01/gamelog/2025/",
      "avgFantasyScore": "22.19",
      "avgSingleGameHigh": "27.42",
      "avgTwoGameHigh": "24.33",
      "avgPTS": "20.4",
      "avgAST": "4.5",
      "avgTRB": "3.7",
      "avgFG3": "2.9",
      "avgBLK": "0.2",
      "avgSTL": "0.9",
      "avgTOV": "2.4",
      "#": "55",
      "MyRanking": "55",
      "Sleeper Rank": "65",
      "Discrepency": "10",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jakob Poeltl",
      "playerUrl": "https://www.basketball-reference.com/players/p/poeltja01/gamelog/2025/",
      "avgFantasyScore": "22.87",
      "avgSingleGameHigh": "27.25",
      "avgTwoGameHigh": "25.46",
      "avgPTS": "13.5",
      "avgAST": "1.9",
      "avgTRB": "9.7",
      "avgFG3": "0",
      "avgBLK": "0.9",
      "avgSTL": "0.9",
      "avgTOV": "1.2",
      "#": "56",
      "MyRanking": "56",
      "Sleeper Rank": "85",
      "Discrepency": "29",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jordan Poole",
      "playerUrl": "https://www.basketball-reference.com/players/p/poolejo01/gamelog/2025/",
      "avgFantasyScore": "19.82",
      "avgSingleGameHigh": "27.17",
      "avgTwoGameHigh": "23.27",
      "avgPTS": "16.3",
      "avgAST": "2.9",
      "avgTRB": "4",
      "avgFG3": "2.5",
      "avgBLK": "0.5",
      "avgSTL": "1.3",
      "avgTOV": "1.4",
      "#": "57",
      "MyRanking": "57",
      "Sleeper Rank": "57",
      "Discrepency": "0",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Onyeka Okongwu",
      "playerUrl": "https://www.basketball-reference.com/players/o/okongon01/gamelog/2025/",
      "avgFantasyScore": "21.05",
      "avgSingleGameHigh": "27.08",
      "avgTwoGameHigh": "24.03",
      "avgPTS": "22.2",
      "avgAST": "4.4",
      "avgTRB": "3.9",
      "avgFG3": "1.1",
      "avgBLK": "0.4",
      "avgSTL": "0.8",
      "avgTOV": "1.4",
      "#": "58",
      "MyRanking": "58",
      "Sleeper Rank": "80",
      "Discrepency": "22",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Trey Murphy III",
      "playerUrl": "https://www.basketball-reference.com/players/m/murphtr02/gamelog/2025/",
      "avgFantasyScore": "22.42",
      "avgSingleGameHigh": "26.79",
      "avgTwoGameHigh": "24.46",
      "avgPTS": "14.1",
      "avgAST": "5.5",
      "avgTRB": "3.7",
      "avgFG3": "2.6",
      "avgBLK": "0.4",
      "avgSTL": "1.6",
      "avgTOV": "1.4",
      "#": "59",
      "MyRanking": "59",
      "Sleeper Rank": "30",
      "Discrepency": "-29",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Deni Avdija",
      "playerUrl": "https://www.basketball-reference.com/players/a/avdijde01/gamelog/2025/",
      "avgFantasyScore": "20.97",
      "avgSingleGameHigh": "26.7",
      "avgTwoGameHigh": "24.2",
      "avgPTS": "19.5",
      "avgAST": "2.1",
      "avgTRB": "6.8",
      "avgFG3": "2.5",
      "avgBLK": "1.5",
      "avgSTL": "0.7",
      "avgTOV": "1.3",
      "#": "60",
      "MyRanking": "60",
      "Sleeper Rank": "50",
      "Discrepency": "-10",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Mark Williams",
      "playerUrl": "https://www.basketball-reference.com/players/w/willima07/gamelog/2025/",
      "avgFantasyScore": "23.03",
      "avgSingleGameHigh": "26.61",
      "avgTwoGameHigh": "24.82",
      "avgPTS": "11.2",
      "avgAST": "3.8",
      "avgTRB": "10.7",
      "avgFG3": "0",
      "avgBLK": "1.1",
      "avgSTL": "0.8",
      "avgTOV": "1.7",
      "#": "55",
      "MyRanking": "55",
      "Sleeper Rank": "100",
      "Discrepency": "45",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "DeMar DeRozan",
      "playerUrl": "https://www.basketball-reference.com/players/d/derozde01/gamelog/2025/",
      "avgFantasyScore": "21.1",
      "avgSingleGameHigh": "26.58",
      "avgTwoGameHigh": "24.04",
      "avgPTS": "19.2",
      "avgAST": "5.3",
      "avgTRB": "6.1",
      "avgFG3": "2.4",
      "avgBLK": "0.4",
      "avgSTL": "1.2",
      "avgTOV": "2.4",
      "#": "62",
      "MyRanking": "62",
      "Sleeper Rank": "105",
      "Discrepency": "43",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "RJ Barrett",
      "playerUrl": "https://www.basketball-reference.com/players/b/barrerj01/gamelog/2025/",
      "avgFantasyScore": "22.72",
      "avgSingleGameHigh": "26.39",
      "avgTwoGameHigh": "25.05",
      "avgPTS": "11.1",
      "avgAST": "1.7",
      "avgTRB": "12.2",
      "avgFG3": "0.1",
      "avgBLK": "2.4",
      "avgSTL": "0.6",
      "avgTOV": "1.5",
      "#": "63",
      "MyRanking": "63",
      "Sleeper Rank": "138",
      "Discrepency": "75",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Darius Garland",
      "playerUrl": "https://www.basketball-reference.com/players/g/garlada01/gamelog/2025/",
      "avgFantasyScore": "21.6",
      "avgSingleGameHigh": "26.27",
      "avgTwoGameHigh": "23.95",
      "avgPTS": "21.4",
      "avgAST": "6",
      "avgTRB": "3.9",
      "avgFG3": "2.3",
      "avgBLK": "0.5",
      "avgSTL": "1.4",
      "avgTOV": "2.1",
      "#": "64",
      "MyRanking": "64",
      "Sleeper Rank": "32",
      "Discrepency": "-32",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "OG Anunoby",
      "playerUrl": "https://www.basketball-reference.com/players/a/anunoog01/gamelog/2025/",
      "avgFantasyScore": "20.57",
      "avgSingleGameHigh": "26.23",
      "avgTwoGameHigh": "23.3",
      "avgPTS": "15.6",
      "avgAST": "1.5",
      "avgTRB": "6.5",
      "avgFG3": "2.2",
      "avgBLK": "2",
      "avgSTL": "0.8",
      "avgTOV": "1.7",
      "#": "65",
      "MyRanking": "65",
      "Sleeper Rank": "73",
      "Discrepency": "8",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Kristaps Porzingis",
      "playerUrl": "https://www.basketball-reference.com/players/p/porzikr01/gamelog/2025/",
      "avgFantasyScore": "23.15",
      "avgSingleGameHigh": "26.21",
      "avgTwoGameHigh": "23.51",
      "avgPTS": "14.4",
      "avgAST": "1.6",
      "avgTRB": "10.2",
      "avgFG3": "0.1",
      "avgBLK": "1",
      "avgSTL": "0.8",
      "avgTOV": "1.7",
      "#": "66",
      "MyRanking": "66",
      "Sleeper Rank": "63",
      "Discrepency": "-3",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Derrick White",
      "playerUrl": "https://www.basketball-reference.com/players/w/whitede01/gamelog/2025/",
      "avgFantasyScore": "21.55",
      "avgSingleGameHigh": "25.85",
      "avgTwoGameHigh": "23.84",
      "avgPTS": "15",
      "avgAST": "2",
      "avgTRB": "8",
      "avgFG3": "1.4",
      "avgBLK": "2.2",
      "avgSTL": "0.7",
      "avgTOV": "1.8",
      "#": "67",
      "MyRanking": "67",
      "Sleeper Rank": "76",
      "Discrepency": "9",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jalen Green",
      "playerUrl": "https://www.basketball-reference.com/players/g/greenja05/gamelog/2025/",
      "avgFantasyScore": "19.98",
      "avgSingleGameHigh": "25.7",
      "avgTwoGameHigh": "22.72",
      "avgPTS": "17",
      "avgAST": "3.7",
      "avgTRB": "3.3",
      "avgFG3": "1.9",
      "avgBLK": "0.5",
      "avgSTL": "1.1",
      "avgTOV": "1.9",
      "#": "68",
      "MyRanking": "68",
      "Sleeper Rank": "88",
      "Discrepency": "20",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "John Collins",
      "playerUrl": "https://www.basketball-reference.com/players/c/collijo01/gamelog/2025/",
      "avgFantasyScore": "22.09",
      "avgSingleGameHigh": "25.67",
      "avgTwoGameHigh": "23.83",
      "avgPTS": "21",
      "avgAST": "3.4",
      "avgTRB": "4.6",
      "avgFG3": "2.9",
      "avgBLK": "0.3",
      "avgSTL": "0.9",
      "avgTOV": "2.5",
      "#": "69",
      "MyRanking": "69",
      "Sleeper Rank": "145",
      "Discrepency": "76",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Coby White",
      "playerUrl": "https://www.basketball-reference.com/players/w/whiteco01/gamelog/2025/",
      "avgFantasyScore": "19.76",
      "avgSingleGameHigh": "25.66",
      "avgTwoGameHigh": "23.28",
      "avgPTS": "18.2",
      "avgAST": "2.1",
      "avgTRB": "7",
      "avgFG3": "2.5",
      "avgBLK": "0.5",
      "avgSTL": "0.6",
      "avgTOV": "1.4",
      "#": "70",
      "MyRanking": "70",
      "Sleeper Rank": "91",
      "Discrepency": "21",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Zach LaVine",
      "playerUrl": "https://www.basketball-reference.com/players/l/lavinza01/gamelog/2025/",
      "avgFantasyScore": "20.93",
      "avgSingleGameHigh": "25.63",
      "avgTwoGameHigh": "23.35",
      "avgPTS": "11.8",
      "avgAST": "2.7",
      "avgTRB": "10.3",
      "avgFG3": "0",
      "avgBLK": "1.1",
      "avgSTL": "0.7",
      "avgTOV": "1.7",
      "#": "71",
      "MyRanking": "71",
      "Sleeper Rank": "60",
      "Discrepency": "-11",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Kawhi Leonard",
      "playerUrl": "https://www.basketball-reference.com/players/l/leonaka01/gamelog/2025/",
      "avgFantasyScore": "23.16",
      "avgSingleGameHigh": "25.57",
      "avgTwoGameHigh": "24.22",
      "avgPTS": "19.3",
      "avgAST": "4.8",
      "avgTRB": "2.7",
      "avgFG3": "3.1",
      "avgBLK": "0.1",
      "avgSTL": "0.9",
      "avgTOV": "2",
      "#": "72",
      "MyRanking": "72",
      "Sleeper Rank": "108",
      "Discrepency": "36",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Julius Randle",
      "playerUrl": "https://www.basketball-reference.com/players/r/randlju01/gamelog/2025/",
      "avgFantasyScore": "21.04",
      "avgSingleGameHigh": "25.52",
      "avgTwoGameHigh": "22.93",
      "avgPTS": "13.4",
      "avgAST": "2.3",
      "avgTRB": "8.9",
      "avgFG3": "0.6",
      "avgBLK": "0.9",
      "avgSTL": "0.9",
      "avgTOV": "1.2",
      "#": "73",
      "MyRanking": "73",
      "Sleeper Rank": "126",
      "Discrepency": "53",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Michael Porter Jr.",
      "playerUrl": "https://www.basketball-reference.com/players/p/portemi01/gamelog/2025/",
      "avgFantasyScore": "20.62",
      "avgSingleGameHigh": "25.28",
      "avgTwoGameHigh": "23.04",
      "avgPTS": "20.5",
      "avgAST": "4.5",
      "avgTRB": "3",
      "avgFG3": "3.5",
      "avgBLK": "0.4",
      "avgSTL": "1.3",
      "avgTOV": "3",
      "#": "74",
      "MyRanking": "74",
      "Sleeper Rank": "118",
      "Discrepency": "44",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jaylen Brown",
      "playerUrl": "https://www.basketball-reference.com/players/b/brownja02/gamelog/2025",
      "avgFantasyScore": "22.86",
      "avgSingleGameHigh": "25.23",
      "avgTwoGameHigh": "24.07",
      "avgPTS": "20.2",
      "avgAST": "3.4",
      "avgTRB": "6.9",
      "avgFG3": "1.6",
      "avgBLK": "0.5",
      "avgSTL": "0.9",
      "avgTOV": "1.4",
      "#": "75",
      "MyRanking": "75",
      "Sleeper Rank": "45",
      "Discrepency": "-30",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Myles Turner",
      "playerUrl": "https://www.basketball-reference.com/players/t/turnemy01/gamelog/2025/",
      "avgFantasyScore": "20.92",
      "avgSingleGameHigh": "25.12",
      "avgTwoGameHigh": "22.66",
      "avgPTS": "12.2",
      "avgAST": "1.1",
      "avgTRB": "7",
      "avgFG3": "1.7",
      "avgBLK": "0.7",
      "avgSTL": "0.4",
      "avgTOV": "1.1",
      "#": "76",
      "MyRanking": "76",
      "Sleeper Rank": "61",
      "Discrepency": "-15",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Paul George",
      "playerUrl": "https://www.basketball-reference.com/players/g/georgpa01/gamelog/2025/",
      "avgFantasyScore": "21.09",
      "avgSingleGameHigh": "25.09",
      "avgTwoGameHigh": "23.1",
      "avgPTS": "15.3",
      "avgAST": "2.5",
      "avgTRB": "10.2",
      "avgFG3": "0",
      "avgBLK": "1.2",
      "avgSTL": "0.7",
      "avgTOV": "1.6",
      "#": "77",
      "MyRanking": "77",
      "Sleeper Rank": "111",
      "Discrepency": "34",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Bobby Portis",
      "playerUrl": "https://www.basketball-reference.com/players/p/portibo01/gamelog/2025/",
      "avgFantasyScore": "19.66",
      "avgSingleGameHigh": "24.87",
      "avgTwoGameHigh": "22.09",
      "avgPTS": "18.5",
      "avgAST": "2.8",
      "avgTRB": "4.5",
      "avgFG3": "2",
      "avgBLK": "0.2",
      "avgSTL": "0.9",
      "avgTOV": "2.1",
      "#": "78",
      "MyRanking": "78",
      "Sleeper Rank": "218",
      "Discrepency": "140",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Tari Eason",
      "playerUrl": "https://www.basketball-reference.com/players/e/easonta01/gamelog/2025/",
      "avgFantasyScore": "18.5",
      "avgSingleGameHigh": "24.76",
      "avgTwoGameHigh": "20.85",
      "avgPTS": "21.8",
      "avgAST": "2.1",
      "avgTRB": "3.2",
      "avgFG3": "3",
      "avgBLK": "0.1",
      "avgSTL": "1.2",
      "avgTOV": "1.8",
      "#": "79",
      "MyRanking": "79",
      "Sleeper Rank": "54",
      "Discrepency": "-25",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Cam Thomas",
      "playerUrl": "https://www.basketball-reference.com/players/t/thomaca02/gamelog/2025/",
      "avgFantasyScore": "19.42",
      "avgSingleGameHigh": "24.73",
      "avgTwoGameHigh": "21.42",
      "avgPTS": "19",
      "avgAST": "1.5",
      "avgTRB": "5.9",
      "avgFG3": "2.9",
      "avgBLK": "0.4",
      "avgSTL": "0.7",
      "avgTOV": "1.4",
      "#": "80",
      "MyRanking": "80",
      "Sleeper Rank": "127",
      "Discrepency": "47",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Brook Lopez",
      "playerUrl": "https://www.basketball-reference.com/players/l/lopezbr01/gamelog/2025/",
      "avgFantasyScore": "18.13",
      "avgSingleGameHigh": "24.73",
      "avgTwoGameHigh": "21.29",
      "avgPTS": "11.7",
      "avgAST": "3.6",
      "avgTRB": "3.7",
      "avgFG3": "2.8",
      "avgBLK": "0.3",
      "avgSTL": "1.2",
      "avgTOV": "1.6",
      "#": "81",
      "MyRanking": "81",
      "Sleeper Rank": "282",
      "Discrepency": "201",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Malik Monk",
      "playerUrl": "https://www.basketball-reference.com/players/m/monkma01/gamelog/2025/",
      "avgFantasyScore": "19.66",
      "avgSingleGameHigh": "24.54",
      "avgTwoGameHigh": "22.23",
      "avgPTS": "9",
      "avgAST": "5.6",
      "avgTRB": "6.1",
      "avgFG3": "1.2",
      "avgBLK": "1",
      "avgSTL": "1.5",
      "avgTOV": "2.6",
      "#": "82",
      "MyRanking": "82",
      "Sleeper Rank": "123",
      "Discrepency": "41",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Fred VanVleet",
      "playerUrl": "https://www.basketball-reference.com/players/v/vanvlfr01/gamelog/2025/",
      "avgFantasyScore": "20.18",
      "avgSingleGameHigh": "24.5",
      "avgTwoGameHigh": "22.04",
      "avgPTS": "12.3",
      "avgAST": "3.4",
      "avgTRB": "5",
      "avgFG3": "1.1",
      "avgBLK": "0.7",
      "avgSTL": "1.3",
      "avgTOV": "2.1",
      "#": "83",
      "MyRanking": "83",
      "Sleeper Rank": "77",
      "Discrepency": "-6",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jalen Suggs",
      "playerUrl": "https://www.basketball-reference.com/players/s/suggsja01/gamelog/2025/",
      "avgFantasyScore": "18.79",
      "avgSingleGameHigh": "24.42",
      "avgTwoGameHigh": "21.77",
      "avgPTS": "9.3",
      "avgAST": "0.9",
      "avgTRB": "7.4",
      "avgFG3": "0.5",
      "avgBLK": "1.1",
      "avgSTL": "0.6",
      "avgTOV": "0.9",
      "#": "84",
      "MyRanking": "84",
      "Sleeper Rank": "71",
      "Discrepency": "-13",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Russell Westbrook",
      "playerUrl": "https://www.basketball-reference.com/players/w/westbru01/gamelog/2025/",
      "avgFantasyScore": "19.09",
      "avgSingleGameHigh": "24.38",
      "avgTwoGameHigh": "21.72",
      "avgPTS": "18.7",
      "avgAST": "4.7",
      "avgTRB": "7.1",
      "avgFG3": "1.6",
      "avgBLK": "0.2",
      "avgSTL": "0.7",
      "avgTOV": "2.8",
      "#": "85",
      "MyRanking": "85",
      "Sleeper Rank": "228",
      "Discrepency": "143",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "P.J. Washington",
      "playerUrl": "https://www.basketball-reference.com/players/w/washipj01/gamelog/2025/",
      "avgFantasyScore": "20.68",
      "avgSingleGameHigh": "24.19",
      "avgTwoGameHigh": "22.27",
      "avgPTS": "18.9",
      "avgAST": "2",
      "avgTRB": "8.2",
      "avgFG3": "1.5",
      "avgBLK": "1",
      "avgSTL": "1",
      "avgTOV": "2.6",
      "#": "86",
      "MyRanking": "86",
      "Sleeper Rank": "114",
      "Discrepency": "28",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Alexandre Sarr",
      "playerUrl": "https://www.basketball-reference.com/players/s/sarral01/gamelog/2025/",
      "avgFantasyScore": "18.94",
      "avgSingleGameHigh": "24.04",
      "avgTwoGameHigh": "21.34",
      "avgPTS": "23.3",
      "avgAST": "4.2",
      "avgTRB": "4.3",
      "avgFG3": "3.2",
      "avgBLK": "0.2",
      "avgSTL": "0.8",
      "avgTOV": "2.8",
      "#": "87",
      "MyRanking": "87",
      "Sleeper Rank": "72",
      "Discrepency": "-15",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Payton Pritchard",
      "playerUrl": "https://www.basketball-reference.com/players/p/pritcpa01/gamelog/2025/",
      "avgFantasyScore": "17.22",
      "avgSingleGameHigh": "23.71",
      "avgTwoGameHigh": "20.59",
      "avgPTS": "14.3",
      "avgAST": "3.5",
      "avgTRB": "3.8",
      "avgFG3": "3.2",
      "avgBLK": "0.2",
      "avgSTL": "0.9",
      "avgTOV": "1",
      "#": "88",
      "MyRanking": "88",
      "Sleeper Rank": "129",
      "Discrepency": "41",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Christian Braun",
      "playerUrl": "https://www.basketball-reference.com/players/b/braunch01/gamelog/2025/",
      "avgFantasyScore": "18.2",
      "avgSingleGameHigh": "23.67",
      "avgTwoGameHigh": "20.86",
      "avgPTS": "18.8",
      "avgAST": "3.4",
      "avgTRB": "4.3",
      "avgFG3": "2.8",
      "avgBLK": "0.4",
      "avgSTL": "0.9",
      "avgTOV": "1.7",
      "#": "89",
      "MyRanking": "89",
      "Sleeper Rank": "131",
      "Discrepency": "42",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Cameron Johnson",
      "playerUrl": "https://www.basketball-reference.com/players/j/johnsca02/gamelog/2025/",
      "avgFantasyScore": "19.55",
      "avgSingleGameHigh": "23.45",
      "avgTwoGameHigh": "21.14",
      "avgPTS": "13.3",
      "avgAST": "6.1",
      "avgTRB": "4.9",
      "avgFG3": "1.3",
      "avgBLK": "0.5",
      "avgSTL": "1.4",
      "avgTOV": "3.2",
      "#": "90",
      "MyRanking": "90",
      "Sleeper Rank": "123",
      "Discrepency": "33",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Keegan Murray",
      "playerUrl": "https://www.basketball-reference.com/players/m/murrake02/gamelog/2025/",
      "avgFantasyScore": "18.09",
      "avgSingleGameHigh": "23.38",
      "avgTwoGameHigh": "20.45",
      "avgPTS": "9.1",
      "avgAST": "1.4",
      "avgTRB": "8.2",
      "avgFG3": "0",
      "avgBLK": "1.3",
      "avgSTL": "0.5",
      "avgTOV": "1.1",
      "#": "91",
      "MyRanking": "91",
      "Sleeper Rank": "94",
      "Discrepency": "3",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Chris Paul",
      "playerUrl": "https://www.basketball-reference.com/players/p/paulch01/gamelog/2025/",
      "avgFantasyScore": "17.87",
      "avgSingleGameHigh": "23.35",
      "avgTwoGameHigh": "21.06",
      "avgPTS": "17.2",
      "avgAST": "5.6",
      "avgTRB": "3.8",
      "avgFG3": "2.1",
      "avgBLK": "0.6",
      "avgSTL": "0.9",
      "avgTOV": "2.4",
      "#": "92",
      "MyRanking": "92",
      "Sleeper Rank": "329",
      "Discrepency": "237",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Santi Aldama",
      "playerUrl": "https://www.basketball-reference.com/players/a/aldamsa01/gamelog/2025/",
      "avgFantasyScore": "18.01",
      "avgSingleGameHigh": "23.3",
      "avgTwoGameHigh": "20.25",
      "avgPTS": "22.2",
      "avgAST": "5.2",
      "avgTRB": "5.6",
      "avgFG3": "2.4",
      "avgBLK": "0.6",
      "avgSTL": "0.9",
      "avgTOV": "3.8",
      "#": "93",
      "MyRanking": "93",
      "Sleeper Rank": "150",
      "Discrepency": "57",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Nicolas Claxton",
      "playerUrl": "https://www.basketball-reference.com/players/c/claxtni01/gamelog/2025/",
      "avgFantasyScore": "18.38",
      "avgSingleGameHigh": "23.28",
      "avgTwoGameHigh": "20.33",
      "avgPTS": "10.3",
      "avgAST": "2.2",
      "avgTRB": "7.4",
      "avgFG3": "0.1",
      "avgBLK": "1.4",
      "avgSTL": "0.9",
      "avgTOV": "1.2",
      "#": "94",
      "MyRanking": "94",
      "Sleeper Rank": "107",
      "Discrepency": "13",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Brandon Miller",
      "playerUrl": "https://www.basketball-reference.com/players/m/millebr02/gamelog/2025/",
      "avgFantasyScore": "21.81",
      "avgSingleGameHigh": "23.27",
      "avgTwoGameHigh": "22.87",
      "avgPTS": "15.1",
      "avgAST": "1.8",
      "avgTRB": "6.1",
      "avgFG3": "1.2",
      "avgBLK": "0.5",
      "avgSTL": "1.5",
      "avgTOV": "1.3",
      "#": "95",
      "MyRanking": "95",
      "Sleeper Rank": "34",
      "Discrepency": "-61",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Kelly Oubre Jr.",
      "playerUrl": "https://www.basketball-reference.com/players/o/oubreke01/gamelog/2025/",
      "avgFantasyScore": "18.98",
      "avgSingleGameHigh": "23.23",
      "avgTwoGameHigh": "21.08",
      "avgPTS": "13",
      "avgAST": "1.8",
      "avgTRB": "5",
      "avgFG3": "1.7",
      "avgBLK": "1.9",
      "avgSTL": "0.6",
      "avgTOV": "1.1",
      "#": "96",
      "MyRanking": "96",
      "Sleeper Rank": "198",
      "Discrepency": "102",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Mikal Bridges",
      "playerUrl": "https://www.basketball-reference.com/players/b/bridgmi01/gamelog/2025/",
      "avgFantasyScore": "18",
      "avgSingleGameHigh": "23.12",
      "avgTwoGameHigh": "20.65",
      "avgPTS": "13",
      "avgAST": "2.4",
      "avgTRB": "6.5",
      "avgFG3": "1.6",
      "avgBLK": "1.5",
      "avgSTL": "0.7",
      "avgTOV": "1.7",
      "#": "97",
      "MyRanking": "97",
      "Sleeper Rank": "79",
      "Discrepency": "-18",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Anfernee Simons",
      "playerUrl": "https://www.basketball-reference.com/players/s/simonan01/gamelog/2025/",
      "avgFantasyScore": "18.52",
      "avgSingleGameHigh": "23.02",
      "avgTwoGameHigh": "21.17",
      "avgPTS": "10.1",
      "avgAST": "2.3",
      "avgTRB": "5.1",
      "avgFG3": "0.2",
      "avgBLK": "0.7",
      "avgSTL": "1.7",
      "avgTOV": "1.4",
      "#": "98",
      "MyRanking": "98",
      "Sleeper Rank": "110",
      "Discrepency": "12",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Andrew Wiggins",
      "playerUrl": "https://www.basketball-reference.com/players/w/wiggian01/gamelog/2025/",
      "avgFantasyScore": "19.28",
      "avgSingleGameHigh": "23",
      "avgTwoGameHigh": "21.56",
      "avgPTS": "16.2",
      "avgAST": "4.3",
      "avgTRB": "5.3",
      "avgFG3": "2.3",
      "avgBLK": "0.5",
      "avgSTL": "1.8",
      "avgTOV": "2.6",
      "#": "99",
      "MyRanking": "99",
      "Sleeper Rank": "144",
      "Discrepency": "45",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Lauri Markkanen",
      "playerUrl": "https://www.basketball-reference.com/players/m/markkla01/gamelog/2025/",
      "avgFantasyScore": "19.19",
      "avgSingleGameHigh": "22.87",
      "avgTwoGameHigh": "20.15",
      "avgPTS": "12.4",
      "avgAST": "1.4",
      "avgTRB": "6.7",
      "avgFG3": "2",
      "avgBLK": "0.9",
      "avgSTL": "0.8",
      "avgTOV": "0.8",
      "#": "100",
      "MyRanking": "100",
      "Sleeper Rank": "47",
      "Discrepency": "-53",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Shaedon Sharpe",
      "playerUrl": "https://www.basketball-reference.com/players/s/sharpsh01/gamelog/2025/",
      "avgFantasyScore": "17.67",
      "avgSingleGameHigh": "22.79",
      "avgTwoGameHigh": "20.18",
      "avgPTS": "13.7",
      "avgAST": "2.2",
      "avgTRB": "5.9",
      "avgFG3": "1.2",
      "avgBLK": "0.8",
      "avgSTL": "1",
      "avgTOV": "1.2",
      "#": "101",
      "MyRanking": "101",
      "Sleeper Rank": "101",
      "Discrepency": "0",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Quentin Grimes",
      "playerUrl": "https://www.basketball-reference.com/players/g/grimequ01/gamelog/2025/",
      "avgFantasyScore": "16.51",
      "avgSingleGameHigh": "22.77",
      "avgTwoGameHigh": "19.3",
      "avgPTS": "24",
      "avgAST": "3.8",
      "avgTRB": "3.3",
      "avgFG3": "2.7",
      "avgBLK": "0.1",
      "avgSTL": "0.6",
      "avgTOV": "2.5",
      "#": "102",
      "MyRanking": "102",
      "Sleeper Rank": "143",
      "Discrepency": "41",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Bilal Coulibaly",
      "playerUrl": "https://www.basketball-reference.com/players/c/coulibi01/gamelog/2025/",
      "avgFantasyScore": "17.03",
      "avgSingleGameHigh": "22.69",
      "avgTwoGameHigh": "19.96",
      "avgPTS": "16.2",
      "avgAST": "3.7",
      "avgTRB": "4",
      "avgFG3": "2.2",
      "avgBLK": "0.9",
      "avgSTL": "1.5",
      "avgTOV": "2.9",
      "#": "103",
      "MyRanking": "103",
      "Sleeper Rank": "90",
      "Discrepency": "-13",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Draymond Green",
      "playerUrl": "https://www.basketball-reference.com/players/g/greendr01/gamelog/2025/",
      "avgFantasyScore": "19.33",
      "avgSingleGameHigh": "22.66",
      "avgTwoGameHigh": "21.3",
      "avgPTS": "21.1",
      "avgAST": "4.1",
      "avgTRB": "3.8",
      "avgFG3": "3.1",
      "avgBLK": "0.4",
      "avgSTL": "0.8",
      "avgTOV": "1.9",
      "#": "104",
      "MyRanking": "104",
      "Sleeper Rank": "201",
      "Discrepency": "97",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Dereck Lively II",
      "playerUrl": "https://www.basketball-reference.com/players/l/livelde01/gamelog/2025/",
      "avgFantasyScore": "17.53",
      "avgSingleGameHigh": "22.65",
      "avgTwoGameHigh": "19.35",
      "avgPTS": "12.3",
      "avgAST": "1.4",
      "avgTRB": "6.8",
      "avgFG3": "0",
      "avgBLK": "1.8",
      "avgSTL": "0.4",
      "avgTOV": "1.2",
      "#": "105",
      "MyRanking": "105",
      "Sleeper Rank": "56",
      "Discrepency": "-49",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Devin Vassell",
      "playerUrl": "https://www.basketball-reference.com/players/v/vassede01/gamelog/2025/",
      "avgFantasyScore": "18.52",
      "avgSingleGameHigh": "22.59",
      "avgTwoGameHigh": "20.79",
      "avgPTS": "14.7",
      "avgAST": "2.3",
      "avgTRB": "7.8",
      "avgFG3": "1.6",
      "avgBLK": "1.1",
      "avgSTL": "1.1",
      "avgTOV": "2.1",
      "#": "106",
      "MyRanking": "106",
      "Sleeper Rank": "93",
      "Discrepency": "-13",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jaden McDaniels",
      "playerUrl": "https://www.basketball-reference.com/players/m/mcdanja02/gamelog/2025/",
      "avgFantasyScore": "17.88",
      "avgSingleGameHigh": "22.58",
      "avgTwoGameHigh": "20.23",
      "avgPTS": "17.6",
      "avgAST": "3.7",
      "avgTRB": "3.2",
      "avgFG3": "2",
      "avgBLK": "0.5",
      "avgSTL": "0.9",
      "avgTOV": "1.6",
      "#": "107",
      "MyRanking": "107",
      "Sleeper Rank": "125",
      "Discrepency": "18",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Daniel Gafford",
      "playerUrl": "https://www.basketball-reference.com/players/g/gaffoda01/gamelog/2025/",
      "avgFantasyScore": "17.73",
      "avgSingleGameHigh": "22.4",
      "avgTwoGameHigh": "20.25",
      "avgPTS": "11.1",
      "avgAST": "3.9",
      "avgTRB": "4.3",
      "avgFG3": "1.7",
      "avgBLK": "0.4",
      "avgSTL": "1.1",
      "avgTOV": "1.2",
      "#": "108",
      "MyRanking": "108",
      "Sleeper Rank": "135",
      "Discrepency": "27",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Keyonte George",
      "playerUrl": "https://www.basketball-reference.com/players/g/georgke01/gamelog/2025/",
      "avgFantasyScore": "18.07",
      "avgSingleGameHigh": "22.31",
      "avgTwoGameHigh": "20.11",
      "avgPTS": "13.9",
      "avgAST": "2.1",
      "avgTRB": "8.4",
      "avgFG3": "1.3",
      "avgBLK": "0.5",
      "avgSTL": "0.7",
      "avgTOV": "1.2",
      "#": "109",
      "MyRanking": "109",
      "Sleeper Rank": "151",
      "Discrepency": "42",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jabari Smith Jr.",
      "playerUrl": "https://www.basketball-reference.com/players/s/smithja05/gamelog/2025/",
      "avgFantasyScore": "16.42",
      "avgSingleGameHigh": "22.31",
      "avgTwoGameHigh": "19.79",
      "avgPTS": "17.6",
      "avgAST": "4",
      "avgTRB": "4.1",
      "avgFG3": "2.1",
      "avgBLK": "0.4",
      "avgSTL": "0.9",
      "avgTOV": "3",
      "#": "110",
      "MyRanking": "110",
      "Sleeper Rank": "113",
      "Discrepency": "3",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Tobias Harris",
      "playerUrl": "https://www.basketball-reference.com/players/h/harrito02/gamelog/2025/",
      "avgFantasyScore": "18.12",
      "avgSingleGameHigh": "22.15",
      "avgTwoGameHigh": "19.96",
      "avgPTS": "12",
      "avgAST": "1.5",
      "avgTRB": "6.4",
      "avgFG3": "1.1",
      "avgBLK": "0.9",
      "avgSTL": "1.7",
      "avgTOV": "1.1",
      "#": "111",
      "MyRanking": "111",
      "Sleeper Rank": "164",
      "Discrepency": "53",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Zach Edey",
      "playerUrl": "https://www.basketball-reference.com/players/e/edeyza01/gamelog/2025/",
      "avgFantasyScore": "16.56",
      "avgSingleGameHigh": "22.14",
      "avgTwoGameHigh": "19.85",
      "avgPTS": "16.3",
      "avgAST": "1.7",
      "avgTRB": "2.6",
      "avgFG3": "3.9",
      "avgBLK": "0.1",
      "avgSTL": "0.9",
      "avgTOV": "1",
      "#": "112",
      "MyRanking": "112",
      "Sleeper Rank": "89",
      "Discrepency": "-23",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Toumani Camara",
      "playerUrl": "https://www.basketball-reference.com/players/c/camarto01/gamelog/2025/",
      "avgFantasyScore": "17.44",
      "avgSingleGameHigh": "22.06",
      "avgTwoGameHigh": "19.62",
      "avgPTS": "18",
      "avgAST": "2.6",
      "avgTRB": "4.5",
      "avgFG3": "2.2",
      "avgBLK": "0.8",
      "avgSTL": "1",
      "avgTOV": "1.6",
      "#": "113",
      "MyRanking": "113",
      "Sleeper Rank": "140",
      "Discrepency": "27",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Clint Capela",
      "playerUrl": "https://www.basketball-reference.com/players/c/capelca01/gamelog/2025/",
      "avgFantasyScore": "16.6",
      "avgSingleGameHigh": "21.88",
      "avgTwoGameHigh": "19.68",
      "avgPTS": "9.2",
      "avgAST": "1",
      "avgTRB": "8.3",
      "avgFG3": "0.3",
      "avgBLK": "1.3",
      "avgSTL": "0.5",
      "avgTOV": "1.3",
      "#": "114",
      "MyRanking": "114",
      "Sleeper Rank": "257",
      "Discrepency": "143",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Bennedict Mathurin",
      "playerUrl": "https://www.basketball-reference.com/players/m/mathube01/gamelog/2025/",
      "avgFantasyScore": "16.13",
      "avgSingleGameHigh": "21.77",
      "avgTwoGameHigh": "18.78",
      "avgPTS": "10.3",
      "avgAST": "3.4",
      "avgTRB": "3.7",
      "avgFG3": "0.7",
      "avgBLK": "0.2",
      "avgSTL": "1.1",
      "avgTOV": "1.8",
      "#": "115",
      "MyRanking": "115",
      "Sleeper Rank": "257",
      "Discrepency": "142",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Bradley Beal",
      "playerUrl": "https://www.basketball-reference.com/players/b/bealbr01/gamelog/2025/",
      "avgFantasyScore": "17.89",
      "avgSingleGameHigh": "21.69",
      "avgTwoGameHigh": "19.59",
      "avgPTS": "11.7",
      "avgAST": "3.4",
      "avgTRB": "5.1",
      "avgFG3": "1.8",
      "avgBLK": "0.2",
      "avgSTL": "1.1",
      "avgTOV": "1.2",
      "#": "116",
      "MyRanking": "116",
      "Sleeper Rank": "186",
      "Discrepency": "70",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Brandin Podziemski",
      "playerUrl": "https://www.basketball-reference.com/players/p/podzibr01/gamelog/2025/",
      "avgFantasyScore": "16.67",
      "avgSingleGameHigh": "21.61",
      "avgTwoGameHigh": "19.02",
      "avgPTS": "8.7",
      "avgAST": "2.4",
      "avgTRB": "7.5",
      "avgFG3": "0",
      "avgBLK": "1.6",
      "avgSTL": "0.6",
      "avgTOV": "1.1",
      "#": "117",
      "MyRanking": "117",
      "Sleeper Rank": "96",
      "Discrepency": "-21",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Norman Powell",
      "playerUrl": "https://www.basketball-reference.com/players/p/powelno01/gamelog/2025/",
      "avgFantasyScore": "18.61",
      "avgSingleGameHigh": "21.56",
      "avgTwoGameHigh": "19.95",
      "avgPTS": "14.4",
      "avgAST": "1.8",
      "avgTRB": "3.6",
      "avgFG3": "2.1",
      "avgBLK": "0.2",
      "avgSTL": "0.9",
      "avgTOV": "1.5",
      "#": "118",
      "MyRanking": "118",
      "Sleeper Rank": "113",
      "Discrepency": "-5",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Kyle Kuzma",
      "playerUrl": "https://www.basketball-reference.com/players/k/kuzmaky01/gamelog/2025/",
      "avgFantasyScore": "15.72",
      "avgSingleGameHigh": "21.52",
      "avgTwoGameHigh": "18.5",
      "avgPTS": "12.2",
      "avgAST": "2",
      "avgTRB": "5.7",
      "avgFG3": "1.2",
      "avgBLK": "0.9",
      "avgSTL": "1.3",
      "avgTOV": "1.2",
      "#": "119",
      "MyRanking": "119",
      "Sleeper Rank": "185",
      "Discrepency": "66",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Wendell Carter Jr.",
      "playerUrl": "https://www.basketball-reference.com/players/c/cartewe01/gamelog/2025/",
      "avgFantasyScore": "15.77",
      "avgSingleGameHigh": "21.18",
      "avgTwoGameHigh": "18.33",
      "avgPTS": "11",
      "avgAST": "2.1",
      "avgTRB": "5.6",
      "avgFG3": "1.5",
      "avgBLK": "0.3",
      "avgSTL": "0.8",
      "avgTOV": "1.2",
      "#": "120",
      "MyRanking": "120",
      "Sleeper Rank": "154",
      "Discrepency": "34",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Yves Missi",
      "playerUrl": "https://www.basketball-reference.com/players/m/missiyv01/gamelog/2025/",
      "avgFantasyScore": "16.91",
      "avgSingleGameHigh": "21.14",
      "avgTwoGameHigh": "19.21",
      "avgPTS": "8.9",
      "avgAST": "1.1",
      "avgTRB": "8.5",
      "avgFG3": "0",
      "avgBLK": "1",
      "avgSTL": "0.6",
      "avgTOV": "0.9",
      "#": "121",
      "MyRanking": "121",
      "Sleeper Rank": "161",
      "Discrepency": "40",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jaden Ivey",
      "playerUrl": "https://www.basketball-reference.com/players/i/iveyja01/gamelog/2025/",
      "avgFantasyScore": "17.58",
      "avgSingleGameHigh": "21.05",
      "avgTwoGameHigh": "20.08",
      "avgPTS": "6.5",
      "avgAST": "1.1",
      "avgTRB": "7.9",
      "avgFG3": "0.2",
      "avgBLK": "1.6",
      "avgSTL": "0.5",
      "avgTOV": "1.1",
      "#": "122",
      "MyRanking": "122",
      "Sleeper Rank": "146",
      "Discrepency": "24",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jerami Grant",
      "playerUrl": "https://www.basketball-reference.com/players/g/grantje01/gamelog/2025/",
      "avgFantasyScore": "16.29",
      "avgSingleGameHigh": "21",
      "avgTwoGameHigh": "18.59",
      "avgPTS": "8.8",
      "avgAST": "7.4",
      "avgTRB": "3.6",
      "avgFG3": "1.7",
      "avgBLK": "0.3",
      "avgSTL": "1.3",
      "avgTOV": "1.6",
      "#": "123",
      "MyRanking": "123",
      "Sleeper Rank": "165",
      "Discrepency": "42",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Donovan Clingan",
      "playerUrl": "https://www.basketball-reference.com/players/c/clingdo01/gamelog/2025/",
      "avgFantasyScore": "15.72",
      "avgSingleGameHigh": "20.96",
      "avgTwoGameHigh": "18.06",
      "avgPTS": "15.4",
      "avgAST": "2.6",
      "avgTRB": "5.2",
      "avgFG3": "1.1",
      "avgBLK": "0.5",
      "avgSTL": "1.1",
      "avgTOV": "1",
      "#": "124",
      "MyRanking": "124",
      "Sleeper Rank": "70",
      "Discrepency": "-54",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Goga Bitadze",
      "playerUrl": "https://www.basketball-reference.com/players/b/bitadgo01/gamelog/2025/",
      "avgFantasyScore": "15.56",
      "avgSingleGameHigh": "20.65",
      "avgTwoGameHigh": "18.28",
      "avgPTS": "14.6",
      "avgAST": "3",
      "avgTRB": "4.3",
      "avgFG3": "2.2",
      "avgBLK": "0.3",
      "avgSTL": "1",
      "avgTOV": "1.9",
      "#": "125",
      "MyRanking": "125",
      "Sleeper Rank": "374",
      "Discrepency": "249",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Stephon Castle",
      "playerUrl": "https://www.basketball-reference.com/players/c/castlst01/gamelog/2025/",
      "avgFantasyScore": "15.96",
      "avgSingleGameHigh": "20.42",
      "avgTwoGameHigh": "18.36",
      "avgPTS": "7.2",
      "avgAST": "2",
      "avgTRB": "6.6",
      "avgFG3": "0",
      "avgBLK": "1.4",
      "avgSTL": "0.7",
      "avgTOV": "1",
      "#": "126",
      "MyRanking": "126",
      "Sleeper Rank": "84",
      "Discrepency": "-42",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Grant Williams",
      "playerUrl": "https://www.basketball-reference.com/players/w/willigr01/gamelog/2025/",
      "avgFantasyScore": "15.59",
      "avgSingleGameHigh": "20.3",
      "avgTwoGameHigh": "18.15",
      "avgPTS": "11.3",
      "avgAST": "2.2",
      "avgTRB": "5.8",
      "avgFG3": "1.7",
      "avgBLK": "0.6",
      "avgSTL": "1.5",
      "avgTOV": "1.4",
      "#": "127",
      "MyRanking": "127",
      "Sleeper Rank": "",
      "Discrepency": "-127",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Ayo Dosunmu",
      "playerUrl": "https://www.basketball-reference.com/players/d/dosunay01/gamelog/2025/",
      "avgFantasyScore": "16.04",
      "avgSingleGameHigh": "20.29",
      "avgTwoGameHigh": "18.33",
      "avgPTS": "12.3",
      "avgAST": "4.5",
      "avgTRB": "3.5",
      "avgFG3": "1.3",
      "avgBLK": "0.4",
      "avgSTL": "0.9",
      "avgTOV": "1.5",
      "#": "128",
      "MyRanking": "128",
      "Sleeper Rank": "157",
      "Discrepency": "29",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Malik Beasley",
      "playerUrl": "https://www.basketball-reference.com/players/b/beaslma01/gamelog/2025/",
      "avgFantasyScore": "15.3",
      "avgSingleGameHigh": "20.1",
      "avgTwoGameHigh": "18.5",
      "avgPTS": "12.5",
      "avgAST": "2.9",
      "avgTRB": "6.4",
      "avgFG3": "1.8",
      "avgBLK": "0.4",
      "avgSTL": "0.8",
      "avgTOV": "1.1",
      "#": "129",
      "MyRanking": "129",
      "Sleeper Rank": "154",
      "Discrepency": "25",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Naji Marshall",
      "playerUrl": "https://www.basketball-reference.com/players/m/marshna01/gamelog/2025/",
      "avgFantasyScore": "15.64",
      "avgSingleGameHigh": "20.02",
      "avgTwoGameHigh": "17.82",
      "avgPTS": "14.7",
      "avgAST": "3.2",
      "avgTRB": "4.8",
      "avgFG3": "1.5",
      "avgBLK": "0.3",
      "avgSTL": "0.5",
      "avgTOV": "1.4",
      "#": "130",
      "MyRanking": "130",
      "Sleeper Rank": "70",
      "Discrepency": "-60",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Donte DiVincenzo",
      "playerUrl": "https://www.basketball-reference.com/players/d/divindo01/gamelog/2025/",
      "avgFantasyScore": "15.86",
      "avgSingleGameHigh": "19.88",
      "avgTwoGameHigh": "17.85",
      "avgPTS": "14.4",
      "avgAST": "2.1",
      "avgTRB": "3.5",
      "avgFG3": "2.3",
      "avgBLK": "1",
      "avgSTL": "0.9",
      "avgTOV": "1.4",
      "#": "131",
      "MyRanking": "131",
      "Sleeper Rank": "120",
      "Discrepency": "-11",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Carlton Carrington",
      "playerUrl": "https://www.basketball-reference.com/players/c/carrica01/gamelog/2025/",
      "avgFantasyScore": "14.53",
      "avgSingleGameHigh": "19.87",
      "avgTwoGameHigh": "17.38",
      "avgPTS": "16.1",
      "avgAST": "1.9",
      "avgTRB": "5.3",
      "avgFG3": "1.4",
      "avgBLK": "0.3",
      "avgSTL": "0.7",
      "avgTOV": "1.9",
      "#": "132",
      "MyRanking": "132",
      "Sleeper Rank": "240",
      "Discrepency": "108",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jrue Holiday",
      "playerUrl": "https://www.basketball-reference.com/players/h/holidjr01/gamelog/2025/",
      "avgFantasyScore": "16.31",
      "avgSingleGameHigh": "19.85",
      "avgTwoGameHigh": "17.67",
      "avgPTS": "12.1",
      "avgAST": "3.4",
      "avgTRB": "3.2",
      "avgFG3": "1.7",
      "avgBLK": "0.5",
      "avgSTL": "0.9",
      "avgTOV": "1.2",
      "#": "133",
      "MyRanking": "133",
      "Sleeper Rank": "331",
      "Discrepency": "198",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Caris LeVert",
      "playerUrl": "https://www.basketball-reference.com/players/l/leverca01/gamelog/2025/",
      "avgFantasyScore": "15.06",
      "avgSingleGameHigh": "19.81",
      "avgTwoGameHigh": "16.64",
      "avgPTS": "10.1",
      "avgAST": "1.6",
      "avgTRB": "4.1",
      "avgFG3": "2.4",
      "avgBLK": "0.5",
      "avgSTL": "1.1",
      "avgTOV": "0.7",
      "#": "134",
      "MyRanking": "134",
      "Sleeper Rank": "155",
      "Discrepency": "21",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Al Horford",
      "playerUrl": "https://www.basketball-reference.com/players/h/horfoal01/gamelog/2025/",
      "avgFantasyScore": "15.97",
      "avgSingleGameHigh": "19.79",
      "avgTwoGameHigh": "17.22",
      "avgPTS": "10.3",
      "avgAST": "3.3",
      "avgTRB": "3.9",
      "avgFG3": "1.1",
      "avgBLK": "0.5",
      "avgSTL": "1.9",
      "avgTOV": "1.8",
      "#": "135",
      "MyRanking": "135",
      "Sleeper Rank": "",
      "Discrepency": "-135",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Kel'el Ware",
      "playerUrl": "https://www.basketball-reference.com/players/w/wareke01/gamelog/2025/",
      "avgFantasyScore": "16.03",
      "avgSingleGameHigh": "19.59",
      "avgTwoGameHigh": "18.25",
      "avgPTS": "10.4",
      "avgAST": "2.3",
      "avgTRB": "5.1",
      "avgFG3": "1.7",
      "avgBLK": "0.8",
      "avgSTL": "1.1",
      "avgTOV": "1.8",
      "#": "136",
      "MyRanking": "136",
      "Sleeper Rank": "387",
      "Discrepency": "251",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Ausar Thompson",
      "playerUrl": "https://www.basketball-reference.com/players/t/thompau01/gamelog/2025/",
      "avgFantasyScore": "15.91",
      "avgSingleGameHigh": "19.55",
      "avgTwoGameHigh": "17.72",
      "avgPTS": "16.8",
      "avgAST": "5.6",
      "avgTRB": "3.8",
      "avgFG3": "2.6",
      "avgBLK": "0.1",
      "avgSTL": "0.7",
      "avgTOV": "2.7",
      "#": "137",
      "MyRanking": "137",
      "Sleeper Rank": "250",
      "Discrepency": "113",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Royce O'Neale",
      "playerUrl": "https://www.basketball-reference.com/players/o/onealro01/gamelog/2025/",
      "avgFantasyScore": "14.39",
      "avgSingleGameHigh": "19.4",
      "avgTwoGameHigh": "16.83",
      "avgPTS": "9",
      "avgAST": "2.1",
      "avgTRB": "6.2",
      "avgFG3": "1.9",
      "avgBLK": "0.8",
      "avgSTL": "0.6",
      "avgTOV": "0.8",
      "#": "138",
      "MyRanking": "138",
      "Sleeper Rank": "230",
      "Discrepency": "92",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Guerschon Yabusele",
      "playerUrl": "https://www.basketball-reference.com/players/y/yabusgu01/gamelog/2025/",
      "avgFantasyScore": "15.13",
      "avgSingleGameHigh": "19.34",
      "avgTwoGameHigh": "17.55",
      "avgPTS": "8.6",
      "avgAST": "2.5",
      "avgTRB": "4.4",
      "avgFG3": "0.6",
      "avgBLK": "0.2",
      "avgSTL": "0.9",
      "avgTOV": "1.5",
      "#": "139",
      "MyRanking": "139",
      "Sleeper Rank": "",
      "Discrepency": "-139",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Luguentz Dort",
      "playerUrl": "https://www.basketball-reference.com/players/d/dortlu01/gamelog/2025/",
      "avgFantasyScore": "14.61",
      "avgSingleGameHigh": "19.28",
      "avgTwoGameHigh": "17.03",
      "avgPTS": "11",
      "avgAST": "4.4",
      "avgTRB": "2.6",
      "avgFG3": "1.4",
      "avgBLK": "0.2",
      "avgSTL": "0.9",
      "avgTOV": "1.3",
      "#": "140",
      "MyRanking": "140",
      "Sleeper Rank": "187",
      "Discrepency": "47",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Spencer Dinwiddie",
      "playerUrl": "https://www.basketball-reference.com/players/d/dinwisp01/gamelog/2025/",
      "avgFantasyScore": "14.25",
      "avgSingleGameHigh": "19.12",
      "avgTwoGameHigh": "16.84",
      "avgPTS": "13.1",
      "avgAST": "1.4",
      "avgTRB": "5",
      "avgFG3": "1.7",
      "avgBLK": "0.4",
      "avgSTL": "0.8",
      "avgTOV": "0.8",
      "#": "141",
      "MyRanking": "141",
      "Sleeper Rank": "391",
      "Discrepency": "250",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Kevin Porter Jr.",
      "playerUrl": "https://www.basketball-reference.com/players/p/porteke02/gamelog/2025/",
      "avgFantasyScore": "13.36",
      "avgSingleGameHigh": "19.1",
      "avgTwoGameHigh": "16.88",
      "avgPTS": "10",
      "avgAST": "5",
      "avgTRB": "3.3",
      "avgFG3": "0.8",
      "avgBLK": "0.2",
      "avgSTL": "1.2",
      "avgTOV": "1.7",
      "#": "142",
      "MyRanking": "142",
      "Sleeper Rank": "133",
      "Discrepency": "-9",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Aaron Gordon",
      "playerUrl": "https://www.basketball-reference.com/players/g/gordoaa01/gamelog/2025/",
      "avgFantasyScore": "16.21",
      "avgSingleGameHigh": "18.79",
      "avgTwoGameHigh": "17.39",
      "avgPTS": "9.1",
      "avgAST": "2",
      "avgTRB": "7.2",
      "avgFG3": "0.5",
      "avgBLK": "0.6",
      "avgSTL": "0.8",
      "avgTOV": "1.1",
      "#": "143",
      "MyRanking": "143",
      "Sleeper Rank": "148",
      "Discrepency": "5",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Gradey Dick",
      "playerUrl": "https://www.basketball-reference.com/players/d/dickgr01/gamelog/2025/",
      "avgFantasyScore": "14.25",
      "avgSingleGameHigh": "18.64",
      "avgTwoGameHigh": "16.51",
      "avgPTS": "12.7",
      "avgAST": "4.1",
      "avgTRB": "3.8",
      "avgFG3": "0.7",
      "avgBLK": "0.2",
      "avgSTL": "0.5",
      "avgTOV": "1.6",
      "#": "144",
      "MyRanking": "144",
      "Sleeper Rank": "174",
      "Discrepency": "30",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Andrew Nembhard",
      "playerUrl": "https://www.basketball-reference.com/players/n/nembhan01/gamelog/2025/",
      "avgFantasyScore": "14.83",
      "avgSingleGameHigh": "18.23",
      "avgTwoGameHigh": "16.32",
      "avgPTS": "9.1",
      "avgAST": "2.2",
      "avgTRB": "4.7",
      "avgFG3": "2.4",
      "avgBLK": "0.5",
      "avgSTL": "0.9",
      "avgTOV": "0.9",
      "#": "145",
      "MyRanking": "145",
      "Sleeper Rank": "269",
      "Discrepency": "124",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Malcolm Brogdon",
      "playerUrl": "https://www.basketball-reference.com/players/b/brogdma01/gamelog/2025/",
      "avgFantasyScore": "14.56",
      "avgSingleGameHigh": "17.91",
      "avgTwoGameHigh": "15.63",
      "avgPTS": "14.7",
      "avgAST": "4.1",
      "avgTRB": "3.7",
      "avgFG3": "1.2",
      "avgBLK": "0.3",
      "avgSTL": "0.9",
      "avgTOV": "2.2",
      "#": "146",
      "MyRanking": "146",
      "Sleeper Rank": "Not Found",
      "Discrepency": "#VALUE!",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Rui Hachimura",
      "playerUrl": "https://www.basketball-reference.com/players/h/hachiru01/gamelog/2025/",
      "avgFantasyScore": "15.43",
      "avgSingleGameHigh": "17.81",
      "avgTwoGameHigh": "16.62",
      "avgPTS": "9.8",
      "avgAST": "4.4",
      "avgTRB": "4.2",
      "avgFG3": "1.7",
      "avgBLK": "0.3",
      "avgSTL": "0.7",
      "avgTOV": "1.7",
      "#": "147",
      "MyRanking": "147",
      "Sleeper Rank": "189",
      "Discrepency": "42",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Jaime Jaquez Jr.",
      "playerUrl": "https://www.basketball-reference.com/players/j/jaqueja01/gamelog/2025/",
      "avgFantasyScore": "12.39",
      "avgSingleGameHigh": "17.12",
      "avgTwoGameHigh": "14.59",
      "avgPTS": "14.8",
      "avgAST": "2.3",
      "avgTRB": "5.7",
      "avgFG3": "1.5",
      "avgBLK": "0.3",
      "avgSTL": "0.6",
      "avgTOV": "2.2",
      "#": "148",
      "MyRanking": "148",
      "Sleeper Rank": "180",
      "Discrepency": "32",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Herbert Jones",
      "playerUrl": "https://www.basketball-reference.com/players/j/joneshe01/gamelog/2025/",
      "avgFantasyScore": "15.68",
      "avgSingleGameHigh": "17.11",
      "avgTwoGameHigh": "16.4",
      "avgPTS": "13.2",
      "avgAST": "3",
      "avgTRB": "4.8",
      "avgFG3": "0.9",
      "avgBLK": "0.2",
      "avgSTL": "1",
      "avgTOV": "1.6",
      "#": "149",
      "MyRanking": "149",
      "Sleeper Rank": "120",
      "Discrepency": "-29",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
    {
      "playerName": "Lonzo Ball",
      "playerUrl": "https://www.basketball-reference.com/players/b/balllo01/gamelog/2025/",
      "avgFantasyScore": "13.91",
      "avgSingleGameHigh": "16.8",
      "avgTwoGameHigh": "15.1",
      "avgPTS": "7.6",
      "avgAST": "3.3",
      "avgTRB": "3.4",
      "avgFG3": "1.9",
      "avgBLK": "0.5",
      "avgSTL": "1.3",
      "avgTOV": "1.2",
      "#": "150",
      "MyRanking": "150",
      "Sleeper Rank": "175",
      "Discrepency": "25",
      "pickNo": "null",
      "roundPicked": "null",
      "pickNoInRound": "null",
      "pickedBy": "null"
    },
  ]